export { useEditor, type Editor, type JSONContent, type UploadedFile } from './useEditor'
export { default as EditorContent } from './EditorContent.vue'
export { default as EditorFixedMenu } from './EditorFixedMenu.vue'
export { default as EditorBubbleMenu } from './EditorBubbleMenu.vue'
export { default as EditorFloatingMenu } from './EditorFloatingMenu.vue'
export * from './menu'

export { default as StarterKit } from '@tiptap/starter-kit'
export { default as Placeholder } from '@tiptap/extension-placeholder'
export { default as Heading } from '@tiptap/extension-heading'
export { default as Link } from '@tiptap/extension-link'
export { default as Code } from '@tiptap/extension-code'
export { default as CodeBlock } from '@tiptap/extension-code-block'
export { Table, TableRow, TableCell, TableHeader } from '@tiptap/extension-table'
export { default as TaskList } from '@tiptap/extension-task-list'
export { default as TaskItem } from '@tiptap/extension-task-item'
export { default as Typography } from '@tiptap/extension-typography'
export { default as TextAlign } from '@tiptap/extension-text-align'
export { default as Color } from '@tiptap/extension-color'
export { default as Highlight } from '@tiptap/extension-highlight'
export { default as Image } from '@tiptap/extension-image'
