/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    LucideBolt: typeof import('~icons/lucide/bolt')['default']
    LucideDownload: typeof import('~icons/lucide/download')['default']
    LucideMail: typeof import('~icons/lucide/mail')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
