/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LucideArrowUpRight: typeof import('~icons/lucide/arrow-up-right')['default']
    LucideBadge: typeof import('~icons/lucide/badge')['default']
    LucideCheck: typeof import('~icons/lucide/check')['default']
    LucideSearch: typeof import('~icons/lucide/search')['default']
    LucideShuffle: typeof import('~icons/lucide/shuffle')['default']
    LucideTrash: typeof import('~icons/lucide/trash')['default']
    LucideTrendingUp: typeof import('~icons/lucide/trending-up')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
