// Generated by tailwind/tokens/build-types.js via `yarn sync-tokens`.
// Do not edit by hand.
//
// Keys are literal, values are `string` (`number` for `fontWeight`). A token
// sync moves values, so regenerating this file after one must produce no diff.

/** A ramp of shades keyed by step (`50`, `100`, … `950`). */
type Ramp = Record<
  | '50' | '100' | '200' | '300' | '400' | '500' | '600' | '700' | '800' | '900'
  | '950',
  string
>

/** The dark gray ramps carry one step the other families do not: `450`. */
type DarkGrayRamp = Record<
  | '50' | '100' | '200' | '300' | '400' | '450' | '500' | '600' | '700' | '800'
  | '900' | '950',
  string
>

/** One map per category. Both themes name the same categories and entries. */
type SemanticColors = {
  surface: Record<
    | 'base' | 'gray-1' | 'gray-2' | 'gray-3' | 'gray-4' | 'gray-5' | 'gray-6'
    | 'gray-7' | 'gray-8' | 'gray-9' | 'gray-10' | 'sidebar' | 'elevation-1'
    | 'elevation-2' | 'elevation-3' | 'red-1' | 'red-2' | 'red-3' | 'red-4'
    | 'red-5' | 'red-6' | 'red-7' | 'red-8' | 'red-9' | 'red-10' | 'blue-1'
    | 'blue-2' | 'blue-3' | 'blue-4' | 'blue-5' | 'blue-6' | 'blue-7' | 'blue-8'
    | 'blue-9' | 'blue-10' | 'green-1' | 'green-2' | 'green-3' | 'green-4'
    | 'green-5' | 'green-6' | 'green-7' | 'green-8' | 'green-9' | 'green-10'
    | 'amber-1' | 'amber-2' | 'amber-3' | 'amber-4' | 'amber-5' | 'amber-6'
    | 'amber-7' | 'amber-8' | 'amber-9' | 'amber-10' | 'violet-1' | 'violet-2'
    | 'violet-3' | 'violet-4' | 'violet-5' | 'violet-6' | 'violet-7'
    | 'violet-8' | 'violet-9' | 'violet-10' | 'yellow-1' | 'yellow-2'
    | 'yellow-3' | 'yellow-4' | 'yellow-5' | 'yellow-6' | 'yellow-7'
    | 'yellow-8' | 'yellow-9' | 'yellow-10' | 'orange-1' | 'orange-2'
    | 'orange-3' | 'orange-4' | 'orange-5' | 'orange-6' | 'orange-7'
    | 'orange-8' | 'orange-9' | 'orange-10' | 'teal-1' | 'teal-2' | 'teal-3'
    | 'teal-4' | 'teal-5' | 'teal-6' | 'teal-7' | 'teal-8' | 'teal-9'
    | 'teal-10' | 'cyan-1' | 'cyan-2' | 'cyan-3' | 'cyan-4' | 'cyan-5'
    | 'cyan-6' | 'cyan-7' | 'cyan-8' | 'cyan-9' | 'cyan-10' | 'purple-1'
    | 'purple-2' | 'purple-3' | 'purple-4' | 'purple-5' | 'purple-6'
    | 'purple-7' | 'purple-8' | 'purple-9' | 'purple-10' | 'pink-1' | 'pink-2'
    | 'pink-3' | 'pink-4' | 'pink-5' | 'pink-6' | 'pink-7' | 'pink-8' | 'pink-9'
    | 'pink-10',
    string
  >
  'surface-alpha': Record<
    | 'base' | 'gray-1' | 'gray-2' | 'gray-3' | 'gray-4' | 'gray-5' | 'gray-6'
    | 'gray-7' | 'gray-8' | 'gray-9' | 'gray-10' | 'sidebar' | 'elevation-1'
    | 'elevation-2' | 'elevation-3',
    string
  >
  ink: Record<
    | 'base' | 'gray-1' | 'gray-2' | 'gray-3' | 'gray-4' | 'gray-5' | 'gray-6'
    | 'gray-7' | 'gray-8' | 'gray-9' | 'red-1' | 'red-2' | 'red-3' | 'red-4'
    | 'red-5' | 'red-6' | 'red-7' | 'red-8' | 'red-9' | 'blue-1' | 'blue-2'
    | 'blue-3' | 'blue-4' | 'blue-5' | 'blue-6' | 'blue-7' | 'blue-8' | 'blue-9'
    | 'green-1' | 'green-2' | 'green-3' | 'green-4' | 'green-5' | 'green-6'
    | 'green-7' | 'green-8' | 'green-9' | 'amber-1' | 'amber-2' | 'amber-3'
    | 'amber-4' | 'amber-5' | 'amber-6' | 'amber-7' | 'amber-8' | 'amber-9'
    | 'violet-1' | 'violet-2' | 'violet-3' | 'violet-4' | 'violet-5'
    | 'violet-6' | 'violet-7' | 'violet-8' | 'violet-9' | 'yellow-1'
    | 'yellow-2' | 'yellow-3' | 'yellow-4' | 'yellow-5' | 'yellow-6'
    | 'yellow-7' | 'yellow-8' | 'yellow-9' | 'orange-1' | 'orange-2'
    | 'orange-3' | 'orange-4' | 'orange-5' | 'orange-6' | 'orange-7'
    | 'orange-8' | 'orange-9' | 'teal-1' | 'teal-2' | 'teal-3' | 'teal-4'
    | 'teal-5' | 'teal-6' | 'teal-7' | 'teal-8' | 'teal-9' | 'cyan-1' | 'cyan-2'
    | 'cyan-3' | 'cyan-4' | 'cyan-5' | 'cyan-6' | 'cyan-7' | 'cyan-8' | 'cyan-9'
    | 'purple-1' | 'purple-2' | 'purple-3' | 'purple-4' | 'purple-5'
    | 'purple-6' | 'purple-7' | 'purple-8' | 'purple-9' | 'pink-1' | 'pink-2'
    | 'pink-3' | 'pink-4' | 'pink-5' | 'pink-6' | 'pink-7' | 'pink-8' | 'pink-9'
    | 'blue-link',
    string
  >
  outline: Record<
    | 'base' | 'gray-1' | 'gray-2' | 'gray-3' | 'gray-4' | 'gray-5' | 'gray-6'
    | 'gray-7' | 'gray-8' | 'gray-9' | 'red-1' | 'red-2' | 'red-3' | 'red-4'
    | 'red-5' | 'red-6' | 'red-7' | 'red-8' | 'red-9' | 'red-10' | 'blue-1'
    | 'blue-2' | 'blue-3' | 'blue-4' | 'blue-5' | 'blue-6' | 'blue-7' | 'blue-8'
    | 'blue-9' | 'blue-10' | 'green-1' | 'green-2' | 'green-3' | 'green-4'
    | 'green-5' | 'green-6' | 'green-7' | 'green-8' | 'green-9' | 'green-10'
    | 'amber-1' | 'amber-2' | 'amber-3' | 'amber-4' | 'amber-5' | 'amber-6'
    | 'amber-7' | 'amber-8' | 'amber-9' | 'amber-10' | 'violet-1' | 'violet-2'
    | 'violet-3' | 'violet-4' | 'violet-5' | 'violet-6' | 'violet-7'
    | 'violet-8' | 'violet-9' | 'violet-10' | 'yellow-1' | 'yellow-2'
    | 'yellow-3' | 'yellow-4' | 'yellow-5' | 'yellow-6' | 'yellow-7'
    | 'yellow-8' | 'yellow-9' | 'yellow-10' | 'orange-1' | 'orange-2'
    | 'orange-3' | 'orange-4' | 'orange-5' | 'orange-6' | 'orange-7'
    | 'orange-8' | 'orange-9' | 'orange-10' | 'teal-1' | 'teal-2' | 'teal-3'
    | 'teal-4' | 'teal-5' | 'teal-6' | 'teal-7' | 'teal-8' | 'teal-9'
    | 'teal-10' | 'cyan-1' | 'cyan-2' | 'cyan-3' | 'cyan-4' | 'cyan-5'
    | 'cyan-6' | 'cyan-7' | 'cyan-8' | 'cyan-9' | 'cyan-10' | 'purple-1'
    | 'purple-2' | 'purple-3' | 'purple-4' | 'purple-5' | 'purple-6'
    | 'purple-7' | 'purple-8' | 'purple-9' | 'purple-10' | 'pink-1' | 'pink-2'
    | 'pink-3' | 'pink-4' | 'pink-5' | 'pink-6' | 'pink-7' | 'pink-8' | 'pink-9'
    | 'pink-10' | 'elevation-1' | 'elevation-2',
    string
  >
  'outline-alpha': Record<
    | 'base' | 'gray-1' | 'gray-2' | 'gray-3' | 'gray-4' | 'gray-5' | 'gray-6'
    | 'gray-7' | 'gray-8' | 'gray-9' | 'elevation-1' | 'elevation-2',
    string
  >
}

/** One `outline` shorthand per colour. Both themes name the same set. */
type FocusRingColors = {
  default: string
  red: string
  green: string
  amber: string
  blue: string
  violet: string
}

/** `fontSize`, `lineHeight`, `letterSpacing` and `fontWeight` for one style. */
export interface TextStyle {
  fontSize: string
  lineHeight: string
  letterSpacing: string
  fontWeight: string
}

/** Letter-spacing per weight, for one size. */
type TrackingByWeight = {
  regular: string
  medium: string
  semibold: string
  bold: string
  black: string
}

/** Every custom property. Goes on `:root`. */
type LightVariables = Record<
  | '--surface-base' | '--surface-gray-1' | '--surface-gray-2'
  | '--surface-gray-3' | '--surface-gray-4' | '--surface-gray-5'
  | '--surface-gray-6' | '--surface-gray-7' | '--surface-gray-8'
  | '--surface-gray-9' | '--surface-gray-10' | '--surface-sidebar'
  | '--surface-elevation-1' | '--surface-elevation-2' | '--surface-elevation-3'
  | '--surface-red-1' | '--surface-red-2' | '--surface-red-3'
  | '--surface-red-4' | '--surface-red-5' | '--surface-red-6'
  | '--surface-red-7' | '--surface-red-8' | '--surface-red-9'
  | '--surface-red-10' | '--surface-blue-1' | '--surface-blue-2'
  | '--surface-blue-3' | '--surface-blue-4' | '--surface-blue-5'
  | '--surface-blue-6' | '--surface-blue-7' | '--surface-blue-8'
  | '--surface-blue-9' | '--surface-blue-10' | '--surface-green-1'
  | '--surface-green-2' | '--surface-green-3' | '--surface-green-4'
  | '--surface-green-5' | '--surface-green-6' | '--surface-green-7'
  | '--surface-green-8' | '--surface-green-9' | '--surface-green-10'
  | '--surface-amber-1' | '--surface-amber-2' | '--surface-amber-3'
  | '--surface-amber-4' | '--surface-amber-5' | '--surface-amber-6'
  | '--surface-amber-7' | '--surface-amber-8' | '--surface-amber-9'
  | '--surface-amber-10' | '--surface-violet-1' | '--surface-violet-2'
  | '--surface-violet-3' | '--surface-violet-4' | '--surface-violet-5'
  | '--surface-violet-6' | '--surface-violet-7' | '--surface-violet-8'
  | '--surface-violet-9' | '--surface-violet-10' | '--surface-yellow-1'
  | '--surface-yellow-2' | '--surface-yellow-3' | '--surface-yellow-4'
  | '--surface-yellow-5' | '--surface-yellow-6' | '--surface-yellow-7'
  | '--surface-yellow-8' | '--surface-yellow-9' | '--surface-yellow-10'
  | '--surface-orange-1' | '--surface-orange-2' | '--surface-orange-3'
  | '--surface-orange-4' | '--surface-orange-5' | '--surface-orange-6'
  | '--surface-orange-7' | '--surface-orange-8' | '--surface-orange-9'
  | '--surface-orange-10' | '--surface-teal-1' | '--surface-teal-2'
  | '--surface-teal-3' | '--surface-teal-4' | '--surface-teal-5'
  | '--surface-teal-6' | '--surface-teal-7' | '--surface-teal-8'
  | '--surface-teal-9' | '--surface-teal-10' | '--surface-cyan-1'
  | '--surface-cyan-2' | '--surface-cyan-3' | '--surface-cyan-4'
  | '--surface-cyan-5' | '--surface-cyan-6' | '--surface-cyan-7'
  | '--surface-cyan-8' | '--surface-cyan-9' | '--surface-cyan-10'
  | '--surface-purple-1' | '--surface-purple-2' | '--surface-purple-3'
  | '--surface-purple-4' | '--surface-purple-5' | '--surface-purple-6'
  | '--surface-purple-7' | '--surface-purple-8' | '--surface-purple-9'
  | '--surface-purple-10' | '--surface-pink-1' | '--surface-pink-2'
  | '--surface-pink-3' | '--surface-pink-4' | '--surface-pink-5'
  | '--surface-pink-6' | '--surface-pink-7' | '--surface-pink-8'
  | '--surface-pink-9' | '--surface-pink-10' | '--surface-alpha-base'
  | '--surface-alpha-gray-1' | '--surface-alpha-gray-2'
  | '--surface-alpha-gray-3' | '--surface-alpha-gray-4'
  | '--surface-alpha-gray-5' | '--surface-alpha-gray-6'
  | '--surface-alpha-gray-7' | '--surface-alpha-gray-8'
  | '--surface-alpha-gray-9' | '--surface-alpha-gray-10'
  | '--surface-alpha-sidebar' | '--surface-alpha-elevation-1'
  | '--surface-alpha-elevation-2' | '--surface-alpha-elevation-3' | '--ink-base'
  | '--ink-gray-1' | '--ink-gray-2' | '--ink-gray-3' | '--ink-gray-4'
  | '--ink-gray-5' | '--ink-gray-6' | '--ink-gray-7' | '--ink-gray-8'
  | '--ink-gray-9' | '--ink-red-1' | '--ink-red-2' | '--ink-red-3'
  | '--ink-red-4' | '--ink-red-5' | '--ink-red-6' | '--ink-red-7'
  | '--ink-red-8' | '--ink-red-9' | '--ink-blue-1' | '--ink-blue-2'
  | '--ink-blue-3' | '--ink-blue-4' | '--ink-blue-5' | '--ink-blue-6'
  | '--ink-blue-7' | '--ink-blue-8' | '--ink-blue-9' | '--ink-green-1'
  | '--ink-green-2' | '--ink-green-3' | '--ink-green-4' | '--ink-green-5'
  | '--ink-green-6' | '--ink-green-7' | '--ink-green-8' | '--ink-green-9'
  | '--ink-amber-1' | '--ink-amber-2' | '--ink-amber-3' | '--ink-amber-4'
  | '--ink-amber-5' | '--ink-amber-6' | '--ink-amber-7' | '--ink-amber-8'
  | '--ink-amber-9' | '--ink-violet-1' | '--ink-violet-2' | '--ink-violet-3'
  | '--ink-violet-4' | '--ink-violet-5' | '--ink-violet-6' | '--ink-violet-7'
  | '--ink-violet-8' | '--ink-violet-9' | '--ink-yellow-1' | '--ink-yellow-2'
  | '--ink-yellow-3' | '--ink-yellow-4' | '--ink-yellow-5' | '--ink-yellow-6'
  | '--ink-yellow-7' | '--ink-yellow-8' | '--ink-yellow-9' | '--ink-orange-1'
  | '--ink-orange-2' | '--ink-orange-3' | '--ink-orange-4' | '--ink-orange-5'
  | '--ink-orange-6' | '--ink-orange-7' | '--ink-orange-8' | '--ink-orange-9'
  | '--ink-teal-1' | '--ink-teal-2' | '--ink-teal-3' | '--ink-teal-4'
  | '--ink-teal-5' | '--ink-teal-6' | '--ink-teal-7' | '--ink-teal-8'
  | '--ink-teal-9' | '--ink-cyan-1' | '--ink-cyan-2' | '--ink-cyan-3'
  | '--ink-cyan-4' | '--ink-cyan-5' | '--ink-cyan-6' | '--ink-cyan-7'
  | '--ink-cyan-8' | '--ink-cyan-9' | '--ink-purple-1' | '--ink-purple-2'
  | '--ink-purple-3' | '--ink-purple-4' | '--ink-purple-5' | '--ink-purple-6'
  | '--ink-purple-7' | '--ink-purple-8' | '--ink-purple-9' | '--ink-pink-1'
  | '--ink-pink-2' | '--ink-pink-3' | '--ink-pink-4' | '--ink-pink-5'
  | '--ink-pink-6' | '--ink-pink-7' | '--ink-pink-8' | '--ink-pink-9'
  | '--ink-blue-link' | '--outline-base' | '--outline-gray-1'
  | '--outline-gray-2' | '--outline-gray-3' | '--outline-gray-4'
  | '--outline-gray-5' | '--outline-gray-6' | '--outline-gray-7'
  | '--outline-gray-8' | '--outline-gray-9' | '--outline-red-1'
  | '--outline-red-2' | '--outline-red-3' | '--outline-red-4'
  | '--outline-red-5' | '--outline-red-6' | '--outline-red-7'
  | '--outline-red-8' | '--outline-red-9' | '--outline-red-10'
  | '--outline-blue-1' | '--outline-blue-2' | '--outline-blue-3'
  | '--outline-blue-4' | '--outline-blue-5' | '--outline-blue-6'
  | '--outline-blue-7' | '--outline-blue-8' | '--outline-blue-9'
  | '--outline-blue-10' | '--outline-green-1' | '--outline-green-2'
  | '--outline-green-3' | '--outline-green-4' | '--outline-green-5'
  | '--outline-green-6' | '--outline-green-7' | '--outline-green-8'
  | '--outline-green-9' | '--outline-green-10' | '--outline-amber-1'
  | '--outline-amber-2' | '--outline-amber-3' | '--outline-amber-4'
  | '--outline-amber-5' | '--outline-amber-6' | '--outline-amber-7'
  | '--outline-amber-8' | '--outline-amber-9' | '--outline-amber-10'
  | '--outline-violet-1' | '--outline-violet-2' | '--outline-violet-3'
  | '--outline-violet-4' | '--outline-violet-5' | '--outline-violet-6'
  | '--outline-violet-7' | '--outline-violet-8' | '--outline-violet-9'
  | '--outline-violet-10' | '--outline-yellow-1' | '--outline-yellow-2'
  | '--outline-yellow-3' | '--outline-yellow-4' | '--outline-yellow-5'
  | '--outline-yellow-6' | '--outline-yellow-7' | '--outline-yellow-8'
  | '--outline-yellow-9' | '--outline-yellow-10' | '--outline-orange-1'
  | '--outline-orange-2' | '--outline-orange-3' | '--outline-orange-4'
  | '--outline-orange-5' | '--outline-orange-6' | '--outline-orange-7'
  | '--outline-orange-8' | '--outline-orange-9' | '--outline-orange-10'
  | '--outline-teal-1' | '--outline-teal-2' | '--outline-teal-3'
  | '--outline-teal-4' | '--outline-teal-5' | '--outline-teal-6'
  | '--outline-teal-7' | '--outline-teal-8' | '--outline-teal-9'
  | '--outline-teal-10' | '--outline-cyan-1' | '--outline-cyan-2'
  | '--outline-cyan-3' | '--outline-cyan-4' | '--outline-cyan-5'
  | '--outline-cyan-6' | '--outline-cyan-7' | '--outline-cyan-8'
  | '--outline-cyan-9' | '--outline-cyan-10' | '--outline-purple-1'
  | '--outline-purple-2' | '--outline-purple-3' | '--outline-purple-4'
  | '--outline-purple-5' | '--outline-purple-6' | '--outline-purple-7'
  | '--outline-purple-8' | '--outline-purple-9' | '--outline-purple-10'
  | '--outline-pink-1' | '--outline-pink-2' | '--outline-pink-3'
  | '--outline-pink-4' | '--outline-pink-5' | '--outline-pink-6'
  | '--outline-pink-7' | '--outline-pink-8' | '--outline-pink-9'
  | '--outline-pink-10' | '--outline-elevation-1' | '--outline-elevation-2'
  | '--outline-alpha-base' | '--outline-alpha-gray-1' | '--outline-alpha-gray-2'
  | '--outline-alpha-gray-3' | '--outline-alpha-gray-4'
  | '--outline-alpha-gray-5' | '--outline-alpha-gray-6'
  | '--outline-alpha-gray-7' | '--outline-alpha-gray-8'
  | '--outline-alpha-gray-9' | '--outline-alpha-elevation-1'
  | '--outline-alpha-elevation-2' | '--gray-50' | '--gray-100' | '--gray-200'
  | '--gray-300' | '--gray-400' | '--gray-500' | '--gray-600' | '--gray-700'
  | '--gray-800' | '--gray-900' | '--gray-950' | '--blue-50' | '--blue-100'
  | '--blue-200' | '--blue-300' | '--blue-400' | '--blue-500' | '--blue-600'
  | '--blue-700' | '--blue-800' | '--blue-900' | '--blue-950' | '--green-50'
  | '--green-100' | '--green-200' | '--green-300' | '--green-400'
  | '--green-500' | '--green-600' | '--green-700' | '--green-800'
  | '--green-900' | '--green-950' | '--red-50' | '--red-100' | '--red-200'
  | '--red-300' | '--red-400' | '--red-500' | '--red-600' | '--red-700'
  | '--red-800' | '--red-900' | '--red-950' | '--orange-50' | '--orange-100'
  | '--orange-200' | '--orange-300' | '--orange-400' | '--orange-500'
  | '--orange-600' | '--orange-700' | '--orange-800' | '--orange-900'
  | '--orange-950' | '--amber-50' | '--amber-100' | '--amber-200'
  | '--amber-300' | '--amber-400' | '--amber-500' | '--amber-600'
  | '--amber-700' | '--amber-800' | '--amber-900' | '--amber-950'
  | '--yellow-50' | '--yellow-100' | '--yellow-200' | '--yellow-300'
  | '--yellow-400' | '--yellow-500' | '--yellow-600' | '--yellow-700'
  | '--yellow-800' | '--yellow-900' | '--yellow-950' | '--teal-50'
  | '--teal-100' | '--teal-200' | '--teal-300' | '--teal-400' | '--teal-500'
  | '--teal-600' | '--teal-700' | '--teal-800' | '--teal-900' | '--teal-950'
  | '--cyan-50' | '--cyan-100' | '--cyan-200' | '--cyan-300' | '--cyan-400'
  | '--cyan-500' | '--cyan-600' | '--cyan-700' | '--cyan-800' | '--cyan-900'
  | '--cyan-950' | '--purple-50' | '--purple-100' | '--purple-200'
  | '--purple-300' | '--purple-400' | '--purple-500' | '--purple-600'
  | '--purple-700' | '--purple-800' | '--purple-900' | '--purple-950'
  | '--pink-50' | '--pink-100' | '--pink-200' | '--pink-300' | '--pink-400'
  | '--pink-500' | '--pink-600' | '--pink-700' | '--pink-800' | '--pink-900'
  | '--pink-950' | '--violet-50' | '--violet-100' | '--violet-200'
  | '--violet-300' | '--violet-400' | '--violet-500' | '--violet-600'
  | '--violet-700' | '--violet-800' | '--violet-900' | '--violet-950'
  | '--gray-alpha-50' | '--gray-alpha-100' | '--gray-alpha-200'
  | '--gray-alpha-300' | '--gray-alpha-400' | '--gray-alpha-500'
  | '--gray-alpha-600' | '--gray-alpha-700' | '--gray-alpha-800'
  | '--gray-alpha-900' | '--gray-alpha-950' | '--elevation-sm'
  | '--elevation-base' | '--elevation-md' | '--elevation-lg' | '--elevation-xl'
  | '--elevation-2xl' | '--focus-outline-default' | '--focus-outline-red'
  | '--focus-outline-green' | '--focus-outline-amber' | '--focus-outline-blue'
  | '--focus-outline-violet' | '--radius-0' | '--radius-1' | '--radius-2'
  | '--radius-3' | '--radius-4' | '--radius-5' | '--radius-6' | '--radius-7'
  | '--radius-8' | '--radius-9' | '--radius-full' | '--radius-none',
  string
>

/** Only the properties dark mode changes. Goes on `[data-theme="dark"]`. */
type DarkVariables = Record<
  | '--surface-base' | '--surface-gray-1' | '--surface-gray-2'
  | '--surface-gray-3' | '--surface-gray-4' | '--surface-gray-5'
  | '--surface-gray-6' | '--surface-gray-7' | '--surface-gray-8'
  | '--surface-gray-9' | '--surface-gray-10' | '--surface-sidebar'
  | '--surface-elevation-1' | '--surface-elevation-2' | '--surface-elevation-3'
  | '--surface-red-1' | '--surface-red-2' | '--surface-red-3'
  | '--surface-red-4' | '--surface-red-5' | '--surface-red-6'
  | '--surface-red-7' | '--surface-red-8' | '--surface-red-9'
  | '--surface-red-10' | '--surface-blue-1' | '--surface-blue-2'
  | '--surface-blue-3' | '--surface-blue-4' | '--surface-blue-5'
  | '--surface-blue-6' | '--surface-blue-7' | '--surface-blue-8'
  | '--surface-blue-9' | '--surface-blue-10' | '--surface-green-1'
  | '--surface-green-2' | '--surface-green-3' | '--surface-green-4'
  | '--surface-green-5' | '--surface-green-6' | '--surface-green-7'
  | '--surface-green-8' | '--surface-green-9' | '--surface-green-10'
  | '--surface-amber-1' | '--surface-amber-2' | '--surface-amber-3'
  | '--surface-amber-4' | '--surface-amber-5' | '--surface-amber-6'
  | '--surface-amber-7' | '--surface-amber-8' | '--surface-amber-9'
  | '--surface-amber-10' | '--surface-violet-1' | '--surface-violet-2'
  | '--surface-violet-3' | '--surface-violet-4' | '--surface-violet-5'
  | '--surface-violet-6' | '--surface-violet-7' | '--surface-violet-8'
  | '--surface-violet-9' | '--surface-violet-10' | '--surface-yellow-1'
  | '--surface-yellow-2' | '--surface-yellow-3' | '--surface-yellow-4'
  | '--surface-yellow-5' | '--surface-yellow-6' | '--surface-yellow-7'
  | '--surface-yellow-8' | '--surface-yellow-9' | '--surface-yellow-10'
  | '--surface-orange-1' | '--surface-orange-2' | '--surface-orange-3'
  | '--surface-orange-4' | '--surface-orange-5' | '--surface-orange-6'
  | '--surface-orange-7' | '--surface-orange-8' | '--surface-orange-9'
  | '--surface-orange-10' | '--surface-teal-1' | '--surface-teal-2'
  | '--surface-teal-3' | '--surface-teal-4' | '--surface-teal-5'
  | '--surface-teal-6' | '--surface-teal-7' | '--surface-teal-8'
  | '--surface-teal-9' | '--surface-teal-10' | '--surface-cyan-1'
  | '--surface-cyan-2' | '--surface-cyan-3' | '--surface-cyan-4'
  | '--surface-cyan-5' | '--surface-cyan-6' | '--surface-cyan-7'
  | '--surface-cyan-8' | '--surface-cyan-9' | '--surface-cyan-10'
  | '--surface-purple-1' | '--surface-purple-2' | '--surface-purple-3'
  | '--surface-purple-4' | '--surface-purple-5' | '--surface-purple-6'
  | '--surface-purple-7' | '--surface-purple-8' | '--surface-purple-9'
  | '--surface-purple-10' | '--surface-pink-1' | '--surface-pink-2'
  | '--surface-pink-3' | '--surface-pink-4' | '--surface-pink-5'
  | '--surface-pink-6' | '--surface-pink-7' | '--surface-pink-8'
  | '--surface-pink-9' | '--surface-pink-10' | '--surface-alpha-base'
  | '--surface-alpha-gray-1' | '--surface-alpha-gray-2'
  | '--surface-alpha-gray-3' | '--surface-alpha-gray-4'
  | '--surface-alpha-gray-5' | '--surface-alpha-gray-6'
  | '--surface-alpha-gray-7' | '--surface-alpha-gray-8'
  | '--surface-alpha-gray-9' | '--surface-alpha-gray-10'
  | '--surface-alpha-sidebar' | '--surface-alpha-elevation-1'
  | '--surface-alpha-elevation-2' | '--surface-alpha-elevation-3' | '--ink-base'
  | '--ink-gray-1' | '--ink-gray-2' | '--ink-gray-3' | '--ink-gray-4'
  | '--ink-gray-5' | '--ink-gray-6' | '--ink-gray-7' | '--ink-gray-8'
  | '--ink-gray-9' | '--ink-red-1' | '--ink-red-2' | '--ink-red-3'
  | '--ink-red-4' | '--ink-red-5' | '--ink-red-6' | '--ink-red-7'
  | '--ink-red-8' | '--ink-red-9' | '--ink-blue-1' | '--ink-blue-2'
  | '--ink-blue-3' | '--ink-blue-4' | '--ink-blue-5' | '--ink-blue-6'
  | '--ink-blue-7' | '--ink-blue-8' | '--ink-blue-9' | '--ink-green-1'
  | '--ink-green-2' | '--ink-green-3' | '--ink-green-4' | '--ink-green-5'
  | '--ink-green-6' | '--ink-green-7' | '--ink-green-8' | '--ink-green-9'
  | '--ink-amber-1' | '--ink-amber-2' | '--ink-amber-3' | '--ink-amber-4'
  | '--ink-amber-5' | '--ink-amber-6' | '--ink-amber-7' | '--ink-amber-8'
  | '--ink-amber-9' | '--ink-violet-1' | '--ink-violet-2' | '--ink-violet-3'
  | '--ink-violet-4' | '--ink-violet-5' | '--ink-violet-6' | '--ink-violet-7'
  | '--ink-violet-8' | '--ink-violet-9' | '--ink-yellow-1' | '--ink-yellow-2'
  | '--ink-yellow-3' | '--ink-yellow-4' | '--ink-yellow-5' | '--ink-yellow-6'
  | '--ink-yellow-7' | '--ink-yellow-8' | '--ink-yellow-9' | '--ink-orange-1'
  | '--ink-orange-2' | '--ink-orange-3' | '--ink-orange-4' | '--ink-orange-5'
  | '--ink-orange-6' | '--ink-orange-7' | '--ink-orange-8' | '--ink-orange-9'
  | '--ink-teal-1' | '--ink-teal-2' | '--ink-teal-3' | '--ink-teal-4'
  | '--ink-teal-5' | '--ink-teal-6' | '--ink-teal-7' | '--ink-teal-8'
  | '--ink-teal-9' | '--ink-cyan-1' | '--ink-cyan-2' | '--ink-cyan-3'
  | '--ink-cyan-4' | '--ink-cyan-5' | '--ink-cyan-6' | '--ink-cyan-7'
  | '--ink-cyan-8' | '--ink-cyan-9' | '--ink-purple-1' | '--ink-purple-2'
  | '--ink-purple-3' | '--ink-purple-4' | '--ink-purple-5' | '--ink-purple-6'
  | '--ink-purple-7' | '--ink-purple-8' | '--ink-purple-9' | '--ink-pink-1'
  | '--ink-pink-2' | '--ink-pink-3' | '--ink-pink-4' | '--ink-pink-5'
  | '--ink-pink-6' | '--ink-pink-7' | '--ink-pink-8' | '--ink-pink-9'
  | '--ink-blue-link' | '--outline-base' | '--outline-gray-1'
  | '--outline-gray-2' | '--outline-gray-3' | '--outline-gray-4'
  | '--outline-gray-5' | '--outline-gray-6' | '--outline-gray-7'
  | '--outline-gray-8' | '--outline-gray-9' | '--outline-red-1'
  | '--outline-red-2' | '--outline-red-3' | '--outline-red-4'
  | '--outline-red-5' | '--outline-red-6' | '--outline-red-7'
  | '--outline-red-8' | '--outline-red-9' | '--outline-red-10'
  | '--outline-blue-1' | '--outline-blue-2' | '--outline-blue-3'
  | '--outline-blue-4' | '--outline-blue-5' | '--outline-blue-6'
  | '--outline-blue-7' | '--outline-blue-8' | '--outline-blue-9'
  | '--outline-blue-10' | '--outline-green-1' | '--outline-green-2'
  | '--outline-green-3' | '--outline-green-4' | '--outline-green-5'
  | '--outline-green-6' | '--outline-green-7' | '--outline-green-8'
  | '--outline-green-9' | '--outline-green-10' | '--outline-amber-1'
  | '--outline-amber-2' | '--outline-amber-3' | '--outline-amber-4'
  | '--outline-amber-5' | '--outline-amber-6' | '--outline-amber-7'
  | '--outline-amber-8' | '--outline-amber-9' | '--outline-amber-10'
  | '--outline-violet-1' | '--outline-violet-2' | '--outline-violet-3'
  | '--outline-violet-4' | '--outline-violet-5' | '--outline-violet-6'
  | '--outline-violet-7' | '--outline-violet-8' | '--outline-violet-9'
  | '--outline-violet-10' | '--outline-yellow-1' | '--outline-yellow-2'
  | '--outline-yellow-3' | '--outline-yellow-4' | '--outline-yellow-5'
  | '--outline-yellow-6' | '--outline-yellow-7' | '--outline-yellow-8'
  | '--outline-yellow-9' | '--outline-yellow-10' | '--outline-orange-1'
  | '--outline-orange-2' | '--outline-orange-3' | '--outline-orange-4'
  | '--outline-orange-5' | '--outline-orange-6' | '--outline-orange-7'
  | '--outline-orange-8' | '--outline-orange-9' | '--outline-orange-10'
  | '--outline-teal-1' | '--outline-teal-2' | '--outline-teal-3'
  | '--outline-teal-4' | '--outline-teal-5' | '--outline-teal-6'
  | '--outline-teal-7' | '--outline-teal-8' | '--outline-teal-9'
  | '--outline-teal-10' | '--outline-cyan-1' | '--outline-cyan-2'
  | '--outline-cyan-3' | '--outline-cyan-4' | '--outline-cyan-5'
  | '--outline-cyan-6' | '--outline-cyan-7' | '--outline-cyan-8'
  | '--outline-cyan-9' | '--outline-cyan-10' | '--outline-purple-1'
  | '--outline-purple-2' | '--outline-purple-3' | '--outline-purple-4'
  | '--outline-purple-5' | '--outline-purple-6' | '--outline-purple-7'
  | '--outline-purple-8' | '--outline-purple-9' | '--outline-purple-10'
  | '--outline-pink-1' | '--outline-pink-2' | '--outline-pink-3'
  | '--outline-pink-4' | '--outline-pink-5' | '--outline-pink-6'
  | '--outline-pink-7' | '--outline-pink-8' | '--outline-pink-9'
  | '--outline-pink-10' | '--outline-elevation-1' | '--outline-elevation-2'
  | '--outline-alpha-base' | '--outline-alpha-gray-1' | '--outline-alpha-gray-2'
  | '--outline-alpha-gray-3' | '--outline-alpha-gray-4'
  | '--outline-alpha-gray-5' | '--outline-alpha-gray-6'
  | '--outline-alpha-gray-7' | '--outline-alpha-gray-8'
  | '--outline-alpha-gray-9' | '--outline-alpha-elevation-1'
  | '--outline-alpha-elevation-2' | '--dark-gray-50' | '--dark-gray-100'
  | '--dark-gray-200' | '--dark-gray-300' | '--dark-gray-400'
  | '--dark-gray-450' | '--dark-gray-500' | '--dark-gray-600'
  | '--dark-gray-700' | '--dark-gray-800' | '--dark-gray-900'
  | '--dark-gray-950' | '--dark-blue-50' | '--dark-blue-100' | '--dark-blue-200'
  | '--dark-blue-300' | '--dark-blue-400' | '--dark-blue-500'
  | '--dark-blue-600' | '--dark-blue-700' | '--dark-blue-800'
  | '--dark-blue-900' | '--dark-blue-950' | '--dark-green-50'
  | '--dark-green-100' | '--dark-green-200' | '--dark-green-300'
  | '--dark-green-400' | '--dark-green-500' | '--dark-green-600'
  | '--dark-green-700' | '--dark-green-800' | '--dark-green-900'
  | '--dark-green-950' | '--dark-red-50' | '--dark-red-100' | '--dark-red-200'
  | '--dark-red-300' | '--dark-red-400' | '--dark-red-500' | '--dark-red-600'
  | '--dark-red-700' | '--dark-red-800' | '--dark-red-900' | '--dark-red-950'
  | '--dark-orange-50' | '--dark-orange-100' | '--dark-orange-200'
  | '--dark-orange-300' | '--dark-orange-400' | '--dark-orange-500'
  | '--dark-orange-600' | '--dark-orange-700' | '--dark-orange-800'
  | '--dark-orange-900' | '--dark-orange-950' | '--dark-amber-50'
  | '--dark-amber-100' | '--dark-amber-200' | '--dark-amber-300'
  | '--dark-amber-400' | '--dark-amber-500' | '--dark-amber-600'
  | '--dark-amber-700' | '--dark-amber-800' | '--dark-amber-900'
  | '--dark-amber-950' | '--dark-yellow-50' | '--dark-yellow-100'
  | '--dark-yellow-200' | '--dark-yellow-300' | '--dark-yellow-400'
  | '--dark-yellow-500' | '--dark-yellow-600' | '--dark-yellow-700'
  | '--dark-yellow-800' | '--dark-yellow-900' | '--dark-yellow-950'
  | '--dark-teal-50' | '--dark-teal-100' | '--dark-teal-200' | '--dark-teal-300'
  | '--dark-teal-400' | '--dark-teal-500' | '--dark-teal-600'
  | '--dark-teal-700' | '--dark-teal-800' | '--dark-teal-900'
  | '--dark-teal-950' | '--dark-cyan-50' | '--dark-cyan-100' | '--dark-cyan-200'
  | '--dark-cyan-300' | '--dark-cyan-400' | '--dark-cyan-500'
  | '--dark-cyan-600' | '--dark-cyan-700' | '--dark-cyan-800'
  | '--dark-cyan-900' | '--dark-cyan-950' | '--dark-purple-50'
  | '--dark-purple-100' | '--dark-purple-200' | '--dark-purple-300'
  | '--dark-purple-400' | '--dark-purple-500' | '--dark-purple-600'
  | '--dark-purple-700' | '--dark-purple-800' | '--dark-purple-900'
  | '--dark-purple-950' | '--dark-pink-50' | '--dark-pink-100'
  | '--dark-pink-200' | '--dark-pink-300' | '--dark-pink-400'
  | '--dark-pink-500' | '--dark-pink-600' | '--dark-pink-700'
  | '--dark-pink-800' | '--dark-pink-900' | '--dark-pink-950'
  | '--dark-violet-50' | '--dark-violet-100' | '--dark-violet-200'
  | '--dark-violet-300' | '--dark-violet-400' | '--dark-violet-500'
  | '--dark-violet-600' | '--dark-violet-700' | '--dark-violet-800'
  | '--dark-violet-900' | '--dark-violet-950' | '--dark-gray-alpha-50'
  | '--dark-gray-alpha-100' | '--dark-gray-alpha-200' | '--dark-gray-alpha-300'
  | '--dark-gray-alpha-400' | '--dark-gray-alpha-450' | '--dark-gray-alpha-500'
  | '--dark-gray-alpha-600' | '--dark-gray-alpha-700' | '--dark-gray-alpha-800'
  | '--dark-gray-alpha-900' | '--dark-gray-alpha-950'
  | '--focus-outline-default' | '--focus-outline-red' | '--focus-outline-green'
  | '--focus-outline-amber' | '--focus-outline-blue' | '--focus-outline-violet',
  string
>

/**
 * Primitive colour ramps, split by theme. These are the raw scales, not the
 * semantic vocabulary — `colors.light.gray[500]`, not `surface-gray-2`.
 * Reach for `semanticColors` unless you specifically want a ramp step.
 */
export declare const colors: {
  light: Record<
    | 'gray' | 'blue' | 'green' | 'red' | 'orange' | 'amber' | 'yellow' | 'teal'
    | 'cyan' | 'purple' | 'pink' | 'violet' | 'gray-alpha',
    Ramp
  >
  dark: {
    gray: DarkGrayRamp
    blue: Ramp
    green: Ramp
    red: Ramp
    orange: Ramp
    amber: Ramp
    yellow: Ramp
    teal: Ramp
    cyan: Ramp
    purple: Ramp
    pink: Ramp
    violet: Ramp
    'gray-alpha': DarkGrayRamp
  }
  overlay: {
    white: Ramp
    black: Ramp
  }
  neutral: {
    white: string
    black: string
    transparent: string
  }
}

/**
 * The semantic vocabulary — `surface`, `surface-alpha`, `ink`, `outline`,
 * `outline-alpha` — resolved to real colours, per theme:
 *
 *   semanticColors.light.surface['gray-2']  // 'oklch(0.964 0 0)'
 *   semanticColors.dark.ink.base            // …
 *
 * Split by theme rather than theme-agnostic, because a consumer outside a
 * frappe-ui page has no `[data-theme]` to resolve against and needs to pick a
 * side. Inside a themed page, prefer the `--<category>-<name>` variables from
 * `cssVariables`, which flip on their own.
 */
export declare const semanticColors: {
  light: SemanticColors
  dark: SemanticColors
}

/**
 * Numbered radius scale `0`–`9` plus `none` and `full`, in px. The named
 * aliases (`sm`, `md`, `lg`, …) were removed in 1.0.0 — see ADR-0006.
 */
export declare const radius: Record<
  | '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | 'full' | 'none',
  string
>

/**
 * The box-shadows frappe-ui renders, as one flat map of composed
 * `box-shadow` strings. Keyed the way the `shadow-*` utilities are: `none`,
 * the six elevation steps, and `DEFAULT` for the bare `shadow` class.
 *
 * Real values, not `var(--elevation-*)` references, so a consumer that has no
 * frappe-ui stylesheet can still paint the shadow. `plugin.js` reads the key
 * list from here and points each Tailwind key at its variable.
 *
 * Only the light steps ship. Espresso 2.0 references `elevation/light/*` on
 * its dark-mode page too, so `elevation.dark` in `effects.js` is not what
 * frappe-ui renders and is not exported. Focus is a separate shape, and a
 * different CSS property: see `focusRing`.
 */
export declare const shadows: {
  none: string
  sm: string
  base: string
  md: string
  lg: string
  xl: string
  '2xl': string
  DEFAULT: string
}

/**
 * The focus ring per theme, one entry per colour (`default`, `red`, `green`,
 * `amber`, `blue`, `violet`).
 *
 * Each value is an `outline` shorthand — `'2px solid #c9c9c9e5'` — not a
 * box-shadow. frappe-ui draws focus with `outline` (ADR-0005), and these are
 * the exact strings behind `--focus-outline-<name>`. Light rings are 2px,
 * dark ones 3px, which is why this one does mode-swap and `shadows` does not.
 */
export declare const focusRing: {
  light: FocusRingColors
  dark: FocusRingColors
}

/**
 * One entry per size, in both families. `fontSize.base` is the text family;
 * `fontSize['p-base']` is the paragraph family, same size with a looser
 * line-height and its own letter-spacing.
 *
 * Objects, not Tailwind's `[size, meta]` tuple form — the tuple is a Tailwind
 * convention and this module does not speak Tailwind. `plugin.js` converts.
 *
 * `letterSpacing` here is the regular weight's. Tracking varies by weight and
 * CSS letter-spacing cannot follow `font-weight`, so per-weight values live in
 * `tracking` and ship as self-contained `text-<size>-<weight>` classes.
 */
export declare const fontSize: Record<
  | '2xs' | 'xs' | 'sm' | 'base' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl'
  | '5xl' | '6xl' | '7xl' | '8xl' | '9xl' | '10xl' | '11xl' | '12xl' | 'p-2xs'
  | 'p-xs' | 'p-sm' | 'p-base' | 'p-md' | 'p-lg' | 'p-xl' | 'p-2xl' | 'p-3xl'
  | 'p-4xl',
  TextStyle
>

/**
 * `regular` is 420, not 400. Inter's 400 reads too light at frappe-ui's sizes,
 * and 420 is the one real customisation in the scale — the rest are stock
 * Inter weights.
 */
export declare const fontWeight: {
  regular: number
  medium: number
  semibold: number
  bold: number
  black: number
}

export declare const fontFamily: {
  text: string
}

/**
 * Letter-spacing per (size, weight), for the `text` and `paragraph` families
 * separately. The only token property that varies by weight.
 */
export declare const tracking: {
  text: {
    '2xs': TrackingByWeight
    xs: TrackingByWeight
    sm: TrackingByWeight
    base: {
      regular: string
      medium: string
      semibold: string
      bold: string
    }
    md: TrackingByWeight
    lg: TrackingByWeight
    xl: TrackingByWeight
    '2xl': TrackingByWeight
    '3xl': TrackingByWeight
    '4xl': TrackingByWeight
    '5xl': TrackingByWeight
    '6xl': TrackingByWeight
    '7xl': TrackingByWeight
    '8xl': TrackingByWeight
    '9xl': TrackingByWeight
    '10xl': TrackingByWeight
    '11xl': TrackingByWeight
    '12xl': TrackingByWeight
  }
  paragraph: Record<
    | '2xs' | 'xs' | 'sm' | 'base' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | '4xl',
    TrackingByWeight
  >
}

/**
 * Every integer 1–128 plus every half step 0.5–19.5, at the canonical 0.25rem
 * step. Stock Tailwind's numeric scale has gaps above 12 (13, 15, 17… are
 * undefined), so `h-17` silently compiles to nothing. Values on the keys
 * Tailwind already defines match its own formula, so filling them is a no-op;
 * the win is the in-between steps.
 *
 * This is the ONE place sizing is declared. Tailwind reads `theme('spacing')`
 * for width, height, size, min/max of both, which is why nothing else
 * declares a sizing block.
 */
export declare const spacing: Record<
  | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12'
  | '13' | '14' | '15' | '16' | '17' | '18' | '19' | '20' | '21' | '22' | '23'
  | '24' | '25' | '26' | '27' | '28' | '29' | '30' | '31' | '32' | '33' | '34'
  | '35' | '36' | '37' | '38' | '39' | '40' | '41' | '42' | '43' | '44' | '45'
  | '46' | '47' | '48' | '49' | '50' | '51' | '52' | '53' | '54' | '55' | '56'
  | '57' | '58' | '59' | '60' | '61' | '62' | '63' | '64' | '65' | '66' | '67'
  | '68' | '69' | '70' | '71' | '72' | '73' | '74' | '75' | '76' | '77' | '78'
  | '79' | '80' | '81' | '82' | '83' | '84' | '85' | '86' | '87' | '88' | '89'
  | '90' | '91' | '92' | '93' | '94' | '95' | '96' | '97' | '98' | '99' | '100'
  | '101' | '102' | '103' | '104' | '105' | '106' | '107' | '108' | '109'
  | '110' | '111' | '112' | '113' | '114' | '115' | '116' | '117' | '118'
  | '119' | '120' | '121' | '122' | '123' | '124' | '125' | '126' | '127'
  | '128' | '0.5' | '1.5' | '2.5' | '3.5' | '4.5' | '5.5' | '6.5' | '7.5'
  | '8.5' | '9.5' | '10.5' | '11.5' | '12.5' | '13.5' | '14.5' | '15.5' | '16.5'
  | '17.5' | '18.5' | '19.5',
  string
>

/** Breakpoint minimums. Not in the Figma export — decided in code. */
export declare const screens: {
  sm: string
  md: string
  lg: string
  xl: string
}

/**
 * Every token as a CSS custom property, keyed by theme:
 *
 *   cssVariables.light['--surface-base']
 *   cssVariables.dark['--surface-base']
 *
 * `light` is the full set, and goes on `:root`. `dark` holds only the
 * properties that change, and goes on `[data-theme="dark"]`; anything absent
 * from it keeps the `light` value. `plugin.js` emits both into the base
 * layer, which is how a frappe-ui page gets them. Read this map directly when
 * you need a token's value somewhere that does not load frappe-ui's
 * stylesheet, such as exported markup or a canvas renderer.
 *
 * Elevation is light-only. It does not flip by theme; see `shadows`.
 */
export declare const cssVariables: {
  light: LightVariables
  dark: DarkVariables
}
