import fs from 'node:fs'
import path from 'node:path'
import type { Plugin, ViteDevServer } from 'vite'

// Author-facing layout: each component owns its docs:
//   src/components/Button/Button.md      (hand-written)
//   src/components/Button/Button.api.md  (auto-generated by propsgen)
//
// VitePress wants every page under its srcDir (`docs/content`). Instead of
// reshaping srcDir or rewrites, this plugin keeps a thin proxy file at
//   docs/content/docs/components/<name>.md
// that simply `@include`s the colocated source. The proxy is auto-managed
// — never edit it by hand.

export interface SourceRootMap {
  // Absolute dir holding `<Component>/<Component>.md` source files.
  sourceDir: string
  // Absolute dir where proxy `<name>.md` files are written.
  proxyDir: string
}

export interface ColocatedComponentDocsOptions {
  // Pairs of source/proxy dirs. Takes precedence over `rootDir` defaults.
  sourceRoots?: SourceRootMap[]
  // Consumer project root. Defaults the proxy dir to
  // `<rootDir>/content/docs/components` and the source dir to
  // `<rootDir>/../src/components`.
  rootDir?: string
}

function rootDirRoots(rootDir: string): SourceRootMap[] {
  return [
    {
      sourceDir: path.resolve(rootDir, '../src/components'),
      proxyDir: path.resolve(rootDir, 'content/docs/components'),
    },
  ]
}

function resolveRoots(options: ColocatedComponentDocsOptions): SourceRootMap[] {
  if (options.sourceRoots && options.sourceRoots.length) return options.sourceRoots
  if (options.rootDir) return rootDirRoots(options.rootDir)
  // No legacy in-repo fallback: warn rather than resolve into nonexistent paths.
  console.warn(
    '[colocatedComponentDocs] no sourceRoots or rootDir provided — skipping proxy generation.',
  )
  return []
}

const PROXY_HEADER =
  '<!-- AUTO-GENERATED by colocatedComponentDocs — do not edit. Source: '

interface Entry {
  name: string // 'Button'
  source: string // absolute path to src/components/Button/Button.md
  proxy: string // absolute path to docs/content/docs/components/button.md
  proxyDir: string // absolute path to the proxy root that owns this entry
}

// Two source layouts, one page either way:
//   <sourceDir>/Button/Button.md   — a folder that documents itself
//   <sourceDir>/docs/BarChart.md   — a family whose components each own a page,
//                                    because one page cannot carry nine APIs
// propsgen reads the same `docs/` rule to place its `<Name>.api.md` tables.
function discover(sourceDir: string, proxyDir: string): Entry[] {
  if (!fs.existsSync(sourceDir)) return []
  const entries: Entry[] = []
  const add = (name: string, source: string) =>
    entries.push({
      name,
      source,
      proxy: path.join(proxyDir, `${name.toLowerCase()}.md`),
      proxyDir,
    })

  const pagesDir = path.join(sourceDir, 'docs')
  if (fs.existsSync(pagesDir)) {
    for (const file of fs.readdirSync(pagesDir)) {
      // `.api.md` is the generated table the page next to it includes.
      if (!file.endsWith('.md') || file.endsWith('.api.md')) continue
      add(path.basename(file, '.md'), path.join(pagesDir, file))
    }
  }

  for (const name of fs.readdirSync(sourceDir)) {
    const source = path.join(sourceDir, name, `${name}.md`)
    if (!fs.existsSync(source)) continue
    add(name, source)
  }
  return entries
}

// VitePress drops an included file's frontmatter, so a page that needs one
// (`outline: false`, to clear the aside for a wide preview) declares it at the
// top of the source and the proxy carries it up.
function leadingFrontmatter(source: string) {
  const content = fs.readFileSync(source, 'utf-8')
  if (!content.startsWith('---\n')) return ''
  const end = content.indexOf('\n---\n', 3)
  return end === -1 ? '' : content.slice(0, end + 5)
}

function proxyContent(entry: Entry) {
  const includePath = path
    .relative(path.dirname(entry.proxy), entry.source)
    .split(path.sep)
    .join('/')
  const sourceRel = path
    .relative(entry.proxyDir, entry.source)
    .split(path.sep)
    .join('/')
  return `${leadingFrontmatter(entry.source)}${PROXY_HEADER}${sourceRel} -->\n<!-- @include: ${includePath} -->\n`
}

function isManagedProxy(filePath: string) {
  if (!fs.existsSync(filePath)) return false
  // Not just the first line: a proxy may open with lifted frontmatter.
  return fs.readFileSync(filePath, 'utf-8').includes(PROXY_HEADER)
}

function writeIfChanged(filePath: string, content: string) {
  if (fs.existsSync(filePath)) {
    const current = fs.readFileSync(filePath, 'utf-8')
    if (current === content) return false
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
  return true
}

export function syncColocatedComponentDocs(
  options: ColocatedComponentDocsOptions = {},
) {
  const roots = resolveRoots(options)
  const allEntries: Entry[] = []

  for (const { sourceDir, proxyDir } of roots) {
    const entries = discover(sourceDir, proxyDir)
    allEntries.push(...entries)
    const expected = new Set(entries.map((e) => e.proxy))

    for (const entry of entries) {
      writeIfChanged(entry.proxy, proxyContent(entry))
    }

    // Remove orphan proxies — only those we created (header check), so
    // hand-written legacy pages like badge.md, legacy.md stay untouched.
    if (fs.existsSync(proxyDir)) {
      for (const name of fs.readdirSync(proxyDir)) {
        const filePath = path.join(proxyDir, name)
        if (expected.has(filePath)) continue
        if (isManagedProxy(filePath)) fs.unlinkSync(filePath)
      }
    }
  }

  return allEntries
}

export default function colocatedComponentDocs(
  options: ColocatedComponentDocsOptions = {},
): Plugin {
  const roots = resolveRoots(options)
  const syncAll = () => syncColocatedComponentDocs(options)
  return {
    name: 'colocated-component-docs',
    enforce: 'pre',
    buildStart() {
      syncAll()
    },
    configureServer(server: ViteDevServer) {
      syncAll()
      const onChange = (file: string) => {
        const matchesRoot = roots.some(({ sourceDir }) =>
          file.startsWith(sourceDir),
        )
        if (!matchesRoot) return
        if (!file.endsWith('.md')) return
        syncAll()
      }
      server.watcher.on('add', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
