import fs from 'node:fs'
import path from 'node:path'
import type { Plugin, ViteDevServer } from 'vite'

// Author-facing layout: each component owns its docs:
//   src/components/Button/Button.md      (hand-written)
//   src/components/Button/Button.api.md  (auto-generated by propsgen)
//   frappe/Link/Link.md                  (Frappe-integrated controls)
//
// VitePress wants every page under its srcDir (`docs/content`). Instead of
// reshaping srcDir or rewrites, this plugin keeps a thin proxy file at
//   docs/content/docs/components/<name>.md
//   docs/content/docs/frappe/<name>.md
// that simply `@include`s the colocated source. The proxy is auto-managed
// — never edit it by hand.

export interface SourceRootMap {
  // Absolute dir holding `<Component>/<Component>.md` source files.
  sourceDir: string
  // Absolute dir where proxy `<name>.md` files are written.
  proxyDir: string
}

export interface ColocatedComponentDocsOptions {
  // Pairs of source/proxy dirs. Takes precedence over `rootDir` defaults.
  sourceRoots?: SourceRootMap[]
  // Consumer project root. Defaults the proxy dirs to
  // `<rootDir>/content/docs/{components,frappe}` and source dirs to
  // `<rootDir>/../src/components` and `<rootDir>/../frappe`.
  rootDir?: string
}

function rootDirRoots(rootDir: string): SourceRootMap[] {
  return [
    {
      sourceDir: path.resolve(rootDir, '../src/components'),
      proxyDir: path.resolve(rootDir, 'content/docs/components'),
    },
    {
      sourceDir: path.resolve(rootDir, '../frappe'),
      proxyDir: path.resolve(rootDir, 'content/docs/frappe'),
    },
  ]
}

function resolveRoots(options: ColocatedComponentDocsOptions): SourceRootMap[] {
  if (options.sourceRoots && options.sourceRoots.length) return options.sourceRoots
  if (options.rootDir) return rootDirRoots(options.rootDir)
  // No legacy in-repo fallback: warn rather than resolve into nonexistent paths.
  console.warn(
    '[colocatedComponentDocs] no sourceRoots or rootDir provided — skipping proxy generation.',
  )
  return []
}

const PROXY_HEADER =
  '<!-- AUTO-GENERATED by colocatedComponentDocs — do not edit. Source: '

interface Entry {
  name: string // 'Button'
  source: string // absolute path to src/components/Button/Button.md
  proxy: string // absolute path to docs/content/docs/components/button.md
  proxyDir: string // absolute path to the proxy root that owns this entry
}

function discover(sourceDir: string, proxyDir: string): Entry[] {
  if (!fs.existsSync(sourceDir)) return []
  const entries: Entry[] = []
  for (const name of fs.readdirSync(sourceDir)) {
    const source = path.join(sourceDir, name, `${name}.md`)
    if (!fs.existsSync(source)) continue
    entries.push({
      name,
      source,
      proxy: path.join(proxyDir, `${name.toLowerCase()}.md`),
      proxyDir,
    })
  }
  return entries
}

function proxyContent(entry: Entry) {
  const includePath = path
    .relative(path.dirname(entry.proxy), entry.source)
    .split(path.sep)
    .join('/')
  const sourceRel = path
    .relative(entry.proxyDir, entry.source)
    .split(path.sep)
    .join('/')
  return `${PROXY_HEADER}${sourceRel} -->\n<!-- @include: ${includePath} -->\n`
}

function isManagedProxy(filePath: string) {
  if (!fs.existsSync(filePath)) return false
  const first = fs.readFileSync(filePath, 'utf-8').split('\n', 1)[0] ?? ''
  return first.startsWith(PROXY_HEADER)
}

function writeIfChanged(filePath: string, content: string) {
  if (fs.existsSync(filePath)) {
    const current = fs.readFileSync(filePath, 'utf-8')
    if (current === content) return false
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
  return true
}

export function syncColocatedComponentDocs(
  options: ColocatedComponentDocsOptions = {},
) {
  const roots = resolveRoots(options)
  const allEntries: Entry[] = []

  for (const { sourceDir, proxyDir } of roots) {
    const entries = discover(sourceDir, proxyDir)
    allEntries.push(...entries)
    const expected = new Set(entries.map((e) => e.proxy))

    for (const entry of entries) {
      writeIfChanged(entry.proxy, proxyContent(entry))
    }

    // Remove orphan proxies — only those we created (header check), so
    // hand-written legacy pages like badge.md, legacy.md stay untouched.
    if (fs.existsSync(proxyDir)) {
      for (const name of fs.readdirSync(proxyDir)) {
        const filePath = path.join(proxyDir, name)
        if (expected.has(filePath)) continue
        if (isManagedProxy(filePath)) fs.unlinkSync(filePath)
      }
    }
  }

  return allEntries
}

export default function colocatedComponentDocs(
  options: ColocatedComponentDocsOptions = {},
): Plugin {
  const roots = resolveRoots(options)
  const syncAll = () => syncColocatedComponentDocs(options)
  return {
    name: 'colocated-component-docs',
    enforce: 'pre',
    buildStart() {
      syncAll()
    },
    configureServer(server: ViteDevServer) {
      syncAll()
      const onChange = (file: string) => {
        const matchesRoot = roots.some(({ sourceDir }) =>
          file.startsWith(sourceDir),
        )
        if (!matchesRoot) return
        if (!file.endsWith('.md')) return
        syncAll()
      }
      server.watcher.on('add', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
