import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { hexToOklch, serializeTokenModule, toOklch } from './build.js'
import colors from './colors.js'
import effects from './effects.js'
import radius from './radius.js'
import typography from './typography.js'

describe('hexToOklch', () => {
  it('converts a 6-digit hex', () => {
    expect(hexToOklch('#ffffff')).toBe('oklch(1 0 0)')
  })

  it('converts an 8-digit hex with alpha', () => {
    expect(hexToOklch('#00000080')).toBe('oklch(0 0 0 / 0.502)')
  })

  it('throws on shorthand hex instead of emitting NaN', () => {
    expect(() => hexToOklch('#fff')).toThrow(/#rrggbb/)
  })
})

describe('toOklch', () => {
  it('passes alias references through untouched', () => {
    expect(toOklch('{light.gray.50}')).toBe('{light.gray.50}')
  })
})

describe('serializeTokenModule', () => {
  const dir = fileURLToPath(new URL('.', import.meta.url))
  const generated = {
    'colors.js': colors,
    'effects.js': effects,
    'radius.js': radius,
    'typography.js': typography,
  }

  it('covers every generated file in this directory', () => {
    const onDisk = readdirSync(dir).filter(
      (f) => f.endsWith('.js') && !f.startsWith('build.'),
    )
    expect(onDisk.sort()).toEqual(Object.keys(generated).sort())
  })

  // A sync run cannot happen here: .figma-export/ is an input, not a committed
  // record. Feed each committed file's own data back through the writer
  // instead. A drift in the emitted format then fails, without a Figma export.
  it.each(Object.entries(generated))(
    'round-trips %s byte for byte',
    (file, data) => {
      expect(serializeTokenModule(data)).toBe(
        readFileSync(join(dir, file), 'utf8'),
      )
    },
  )

  it('emits a header and a JSON body', () => {
    expect(serializeTokenModule({ a: 1 })).toBe(
      '// Generated by tailwind/tokens/build.js via `yarn sync-tokens`.\n' +
        '// Do not edit by hand.\n' +
        '\n' +
        'export default {\n  "a": 1\n}\n',
    )
  })
})
