/**
 * Type generator: writes `tailwind/tokens.d.ts` from `tailwind/tokens.js`.
 *
 *   Input:   tailwind/tokens.js  (imported, and read as text for its JSDoc)
 *   Output:  tailwind/tokens.d.ts
 *
 * Every key in the declaration file comes from the runtime module, so the two
 * cannot drift. Values stay `string` (or `number` for a font weight, in
 * `fontWeight` and in each `fontSize` entry): a token sync moves values, and
 * a value change must never be a type change.
 *
 * `build.js` calls this after it writes the token data, so `yarn sync-tokens`
 * regenerates both. Run `yarn sync-token-types` to regenerate the declaration
 * file alone, which is what an edit to `tokens.js` needs.
 *
 * A committed file that differs from this generator's output fails the test in
 * `build.test.js`, byte for byte.
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath, pathToFileURL } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, '..', '..')
const SOURCE = path.join(REPO_ROOT, 'tailwind', 'tokens.js')
const OUTPUT = path.join(REPO_ROOT, 'tailwind', 'tokens.d.ts')

const HEADER = `// Generated by tailwind/tokens/build-types.js via \`yarn sync-tokens\`.
// Do not edit by hand.
//
// Keys are literal, values are \`string\` (\`number\` for a font weight). A token
// sync moves values, so regenerating this file after one must produce no diff.
`

const PRINT_WIDTH = 80

// Above this many keys an object becomes \`Record<'a' | 'b', T>\`, at or below
// it stays a named-property type. Small maps read better one key per line and
// hover better; a 125-entry colour category does not.
const MAX_NAMED_KEYS = 8

/**
 * Shapes worth a name of their own, addressed by their path in the token tree.
 * `*` matches one segment and names the first child that reaches it; a later
 * sibling with a different shape stays inline, which is how `tracking.text`
 * shows that `base` carries no `black` entry.
 *
 * Naming is the only thing this table decides. Keys always come from the
 * runtime value, so a shape that stops matching its siblings falls back to an
 * inline type rather than a wrong one.
 */
const ALIASES = [
  {
    path: 'colors.light.*',
    name: 'Ramp',
    doc: 'A ramp of shades keyed by step (`50`, `100`, … `950`).',
  },
  {
    path: 'colors.dark.gray',
    name: 'DarkGrayRamp',
    doc: 'The dark gray ramps carry one step the other families do not: `450`.',
  },
  {
    path: 'semanticColors.light',
    name: 'SemanticColors',
    doc: 'One map per category. Both themes name the same categories and entries.',
  },
  {
    path: 'focusRing.light',
    name: 'FocusRingColors',
    doc: 'One `outline` shorthand per colour. Both themes name the same set.',
  },
  {
    path: 'fontSize.*',
    name: 'TextStyle',
    doc: '`fontSize`, `lineHeight`, `letterSpacing` and `fontWeight` for one style.',
    form: 'interface',
    exported: true,
  },
  {
    path: 'tracking.text.*',
    name: 'TrackingByWeight',
    doc: 'Letter-spacing per weight, for one size.',
  },
  {
    path: 'cssVariables.light',
    name: 'LightVariables',
    doc: 'The `:root` layer: every property except the dark ramps.',
  },
  {
    path: 'cssVariables.dark',
    name: 'DarkVariables',
    doc: 'The `[data-theme="dark"]` layer: the semantic and focus properties re-valued, plus the dark ramps.',
  },
]

function matchAlias(nodePath) {
  const segments = nodePath.split('.')
  return ALIASES.find((alias) => {
    const pattern = alias.path.split('.')
    if (pattern.length !== segments.length) return false
    return pattern.every((part, i) => part === '*' || part === segments[i])
  })
}

// ---------- FORMATTING ----------

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

const quote = (key) => `'${key}'`
const propertyKey = (key) => (IDENTIFIER.test(key) ? key : quote(key))
const pad = (indent) => ' '.repeat(indent)

// A union packed to the print width, every line starting with `|`. One key per
// line would be 1,100 lines for `cssVariables` alone.
function unionLines(keys, indent) {
  const lines = []
  let line = ''
  for (const key of keys) {
    const next = line ? `${line} | ${quote(key)}` : `| ${quote(key)}`
    if (line && indent + next.length > PRINT_WIDTH) {
      lines.push(pad(indent) + line)
      line = `| ${quote(key)}`
    } else {
      line = next
    }
  }
  lines.push(pad(indent) + line)
  return lines
}

function recordType(keys, valueType, indent) {
  const inline = `Record<${keys.map(quote).join(' | ')}, ${valueType}>`
  if (!valueType.includes('\n') && indent + inline.length <= PRINT_WIDTH) {
    return inline
  }
  const union = unionLines(keys, indent + 2).join('\n')
  return `Record<\n${union},\n${pad(indent + 2)}${valueType}\n${pad(indent)}>`
}

function objectType(pairs, indent) {
  const body = pairs
    .map(([key, type]) => `${pad(indent + 2)}${propertyKey(key)}: ${type}`)
    .join('\n')
  return `{\n${body}\n${pad(indent)}}`
}

function docComment(text, indent) {
  if (!text) return ''
  const line = `${pad(indent)}/** ${text} */`
  if (line.length <= PRINT_WIDTH) return line + '\n'
  return `${pad(indent)}/**\n${pad(indent)} * ${text}\n${pad(indent)} */\n`
}

// ---------- WALK ----------

/**
 * Builds the type for one runtime value. `emit` wraps it with the alias table,
 * so a child that earned a name is referenced by name here.
 */
function build(value, nodePath, indent, state) {
  if (typeof value === 'number') return 'number'
  if (typeof value === 'string') return 'string'
  if (value === null || typeof value !== 'object') {
    throw new Error(`cannot type ${nodePath}: ${typeof value}`)
  }

  const entries = Object.entries(value)
  if (entries.length === 0) throw new Error(`empty token map at ${nodePath}`)

  const types = entries.map(([key, child]) =>
    emit(child, `${nodePath}.${key}`, indent + 2, state),
  )
  const uniform = types.every((type) => type === types[0])

  if (uniform && entries.length > MAX_NAMED_KEYS) {
    return recordType(
      entries.map(([key]) => key),
      types[0],
      indent,
    )
  }
  return objectType(
    entries.map(([key], i) => [key, types[i]]),
    indent,
  )
}

/**
 * Returns the type text for a value, or the name of the alias that holds it.
 *
 * An alias is keyed on the type text, not on the path, so two paths that build
 * the same type share one name. That is what collapses `semanticColors.dark`
 * onto `semanticColors.light` and every light ramp onto `Ramp`.
 */
function emit(value, nodePath, indent, state) {
  const memo = `${nodePath} @${indent}`
  if (state.memo.has(memo)) return state.memo.get(memo)

  const canonical = build(value, nodePath, 0, state)
  let result = state.byText.get(canonical)

  if (!result) {
    const alias = matchAlias(nodePath)
    if (alias && !state.byName.has(alias.name)) {
      state.byName.set(alias.name, { ...alias, text: canonical })
      state.byText.set(canonical, alias.name)
      result = alias.name
    }
  }
  if (!result) {
    result = indent === 0 ? canonical : build(value, nodePath, indent, state)
  }

  state.memo.set(memo, result)
  return result
}

// ---------- SOURCE ----------

// Export order and JSDoc both come from tokens.js: a namespace object sorts its
// keys, and the comments belong beside the values, not duplicated here.
function readSource() {
  const source = fs.readFileSync(SOURCE, 'utf8')
  const order = [...source.matchAll(/^export const (\w+)/gm)].map((m) => m[1])
  // Each block is matched on its own, then tested for what follows it. One
  // pattern spanning both would backtrack across an earlier `*/` and staple
  // the module header onto the first documented export.
  const docs = new Map()
  for (const block of source.matchAll(/\/\*\*[\s\S]*?\*\//g)) {
    const after = source.slice(block.index + block[0].length)
    const owner = after.match(/^\s*export const (\w+)/)
    if (owner) docs.set(owner[1], block[0])
  }
  return { order, docs }
}

// ---------- GENERATE ----------

export async function generateTokenTypes() {
  const { order, docs } = readSource()
  const tokens = await import(pathToFileURL(SOURCE).href)

  const runtime = Object.keys(tokens).sort()
  if (runtime.join() !== [...order].sort().join()) {
    throw new Error(
      `tokens.js exports ${runtime.join(', ')} but the source lists ${order.join(', ')}`,
    )
  }

  const state = { byName: new Map(), byText: new Map(), memo: new Map() }
  const declarations = order.map((name) => {
    const type = emit(tokens[name], name, 0, state)
    return `${docs.get(name) ? docs.get(name) + '\n' : ''}export declare const ${name}: ${type}\n`
  })

  const aliases = [...state.byName.values()].map((alias) => {
    const doc = docComment(alias.doc, 0)
    if (alias.form === 'interface') {
      return `${doc}${alias.exported ? 'export ' : ''}interface ${alias.name} ${alias.text}\n`
    }
    return `${doc}${alias.exported ? 'export ' : ''}type ${alias.name} = ${alias.text}\n`
  })

  return [HEADER, ...aliases, ...declarations].join('\n')
}

export async function writeTokenTypes() {
  fs.writeFileSync(OUTPUT, await generateTokenTypes())
  console.log(`  wrote ${path.relative(REPO_ROOT, OUTPUT)}`)
}

const scriptPath = fileURLToPath(import.meta.url)
const invokedPath = process.argv[1]
if (
  invokedPath &&
  fs.realpathSync(invokedPath) === fs.realpathSync(scriptPath)
) {
  await writeTokenTypes()
}
