import fs from 'fs'
import path from 'path'

/**
 * VitePress' dead-link check validates paths, not `#fragments`. A link to a
 * heading that no longer exists still builds, and lands the reader at the top
 * of the page. This module resolves every heading id the way VitePress does,
 * so a test can check the fragments too.
 *
 * The slug rules mirror `@mdit-vue/shared`, which VitePress bundles. They are
 * not GitHub's rules: GitHub keeps repeated hyphens (`a--b`), VitePress
 * collapses them (`a-b`), and neither treats an em dash the same way.
 */

const rControl = /[\u0000-\u001f]/g
const rSpecial = /[\s~`!@#$%^&*()\-_+=[\]{}|\\;:"'“”‘’<>,.?/]+/g
const rCombining = /[\u0300-\u036f]/g

export function slugify(text: string): string {
  return text
    .normalize('NFKD')
    .replace(rCombining, '')
    .replace(rControl, '')
    .replace(rSpecial, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/^(\d)/, '_$1')
    .toLowerCase()
}

/** Strip the inline markdown that the renderer drops before it slugs. */
function headingText(raw: string): string {
  return raw
    .replace(/`([^`]*)`/g, '$1')
    .replace(/\*\*?([^*]*)\*\*?/g, '$1')
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
}

/** Every heading id on one page, including VitePress' `-1` de-duplication. */
export function headingIds(source: string): Set<string> {
  const ids = new Set<string>()
  const seen = new Map<string, number>()
  let inFence = false

  for (const line of source.replace(/^---\n[\s\S]*?\n---\n/, '').split('\n')) {
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence
      continue
    }
    if (inFence) continue

    const heading = /^#{1,6}\s+(.*?)\s*$/.exec(line)
    if (!heading) continue

    const explicit = /\{#([^}]+)\}\s*$/.exec(heading[1])
    const id = explicit ? explicit[1] : slugify(headingText(heading[1]))

    const count = seen.get(id) ?? 0
    seen.set(id, count + 1)
    ids.add(count === 0 ? id : `${id}-${count}`)
  }

  return ids
}

export interface BrokenLink {
  file: string
  href: string
}

/** A directory of markdown, and the site route its files are served under. */
export interface DocsRoot {
  dir: string
  route: string
  /**
   * Colocated pages are flattened: `src/charts/docs/BarChart.md` proxies to
   * `/docs/charts/barchart`, so the nesting and the case are both dropped.
   */
  flatten?: boolean
}

/** Drop fenced blocks, so an example link is not read as a real one. */
function stripFences(source: string): string {
  return source.replace(/^[ \t]*(```|~~~)[\s\S]*?^[ \t]*\1[ \t]*$/gm, '')
}

/**
 * Inline what `<!-- @include: ./x.md -->` pulls in, because those headings
 * get ids on the rendered page too. Every component page takes its
 * `## API Reference` from the generated `.api.md` next to it.
 */
function expandIncludes(source: string, file: string, depth = 0): string {
  if (depth > 4) return source
  return source.replace(
    /<!--\s*@include:\s*([^\s>]+?)\s*-->/g,
    (whole, href: string) => {
      // The `#region` form includes a named slice; leave it to the renderer.
      const target = path.resolve(path.dirname(file), href.split('#')[0])
      if (href.includes('#') || !fs.existsSync(target)) return whole
      return expandIncludes(fs.readFileSync(target, 'utf8'), target, depth + 1)
    },
  )
}

/**
 * A generated `@include` stub holds no headings of its own. It is untracked,
 * so it exists after a docs build and not in a fresh checkout; skip it either
 * way and read the colocated source instead.
 */
function isProxyPage(file: string): boolean {
  return fs.readFileSync(file, 'utf8').includes('AUTO-GENERATED by colocated')
}

/**
 * One spelling per page, so a link and its target agree. `a/index.md`,
 * `a/index`, `a/` and `a` are all the same route.
 */
function canonical(route: string): string {
  return route
    .replace(/\.md$/, '')
    .replace(/\/index$/, '')
    .replace(/\/$/, '')
}

/** The site route of a markdown file, e.g. `/docs/migration`. */
function routeOf(file: string, root: DocsRoot): string {
  const rest = path.relative(root.dir, file).split(path.sep).join('/')
  return canonical(`${root.route}/${rest}`)
}

/**
 * Report every `#fragment` link with no matching heading.
 *
 * `roots` must list every directory the site serves, because a link is only
 * checked when its target page is indexed. Colocated component pages live
 * beside their source and proxy in through `@include`, so their directory is
 * a root of its own — see `colocatedRoots` in `docs/.vitepress/config.ts`.
 */
export function findBrokenAnchorLinks(roots: DocsRoot[]): BrokenLink[] {
  const pages: { file: string; route: string }[] = []

  const walk = (dir: string, root: DocsRoot) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const child = path.join(dir, entry.name)
      if (entry.isDirectory()) walk(child, root)
      else if (entry.name.endsWith('.md') && !isProxyPage(child))
        pages.push({ file: child, route: routeOf(child, root) })
    }
  }

  // The two shapes `colocatedComponentDocs` proxies: `<dir>/docs/<Page>.md`
  // for a family, and `<dir>/<Name>/<Name>.md` for one component.
  const collect = (root: DocsRoot) => {
    const add = (name: string, file: string) =>
      pages.push({ file, route: `${root.route}/${name.toLowerCase()}` })

    const pagesDir = path.join(root.dir, 'docs')
    if (fs.existsSync(pagesDir))
      for (const file of fs.readdirSync(pagesDir))
        if (file.endsWith('.md') && !file.endsWith('.api.md'))
          add(path.basename(file, '.md'), path.join(pagesDir, file))

    for (const name of fs.readdirSync(root.dir)) {
      const file = path.join(root.dir, name, `${name}.md`)
      if (fs.existsSync(file)) add(name, file)
    }
  }

  for (const root of roots) {
    if (!fs.existsSync(root.dir)) continue
    if (root.flatten) collect(root)
    else walk(root.dir, root)
  }

  const read = (file: string) =>
    expandIncludes(fs.readFileSync(file, 'utf8'), file)

  const ids = new Map(
    pages.map(({ file, route }) => [route, headingIds(read(file))]),
  )

  const broken: BrokenLink[] = []
  for (const { file, route } of pages) {
    const source = stripFences(read(file))
    for (const [, href] of source.matchAll(/\]\(([^)\s]*#[^)\s]+)\)/g)) {
      const [page, fragment] = href.split('#')

      // Off-site and protocol links carry no route this check can resolve.
      if (/^[a-z]+:/i.test(page)) continue

      let target: string
      if (page === '') target = route
      else if (page.startsWith('/')) target = canonical(page)
      else
        target = canonical(path.posix.resolve(path.posix.dirname(route), page))

      const pageIds = ids.get(target)
      // A page outside `roots` (a repo file, say) has no ids to check against.
      if (!pageIds) continue
      if (!pageIds.has(fragment)) broken.push({ file, href })
    }
  }

  return broken
}
