import { describe, expect, it } from 'vitest'

import {
  diffApiTables,
  formatDifferences,
  parseApiTables,
  summarizeDifference,
} from './api-tables'
import { normalizeUnionOrder, splitUnionMembers } from './type-unions'

// Mirrors what propsgen writes: a `<script setup>` block of row arrays, then
// the markup that renders them.
function apiFile(script: string) {
  return `<!-- Auto Generated by scripts/propsgen.ts -->
<script setup>
  import PropsTable from '@/components/Docs/PropsTable.vue'
${script}
</script>

## API Reference

<PropsTable name="Toast" :data="propsData"/>
`
}

const TOAST = apiFile(`
  const propsData = [
  {
    name: 'title',
    description: 'Main line of the toast.',
    required: false,
    type: 'string',
    default: '""'
  },
  {
    name: 'type',
    description: 'Visual tone of the toast',
    required: false,
    type: '"error" | "success" | "info" | "warning"'
  }
]

  const emitsData = [
  {
    name: 'close',
    description: 'Fired when the component closes.',
    type: '[]'
  },
  {
    name: 'update:open',
    description: 'Fired when the open state changes.',
    type: '[value: boolean]'
  }
]`)

function diffAgainstToast(current: string) {
  return diffApiTables(
    parseApiTables(TOAST, 'Toast'),
    parseApiTables(current, 'Toast'),
  )
}

describe('parseApiTables', () => {
  it('reads one table per component and kind', () => {
    const tables = parseApiTables(TOAST, 'Toast')

    expect(tables).toHaveLength(2)
    expect(tables.map((t) => [t.component, t.kind])).toEqual([
      ['Toast', 'prop'],
      ['Toast', 'emit'],
    ])
    expect(tables[0].entries.map((e) => e.name)).toEqual(['title', 'type'])
  })

  it('reads every field of a row', () => {
    const [props] = parseApiTables(TOAST, 'Toast')

    expect(props.entries[0]).toEqual({
      name: 'title',
      fields: {
        description: 'Main line of the toast.',
        required: 'false',
        type: 'string',
        default: '""',
      },
    })
  })

  it('names each component from its array in a multi-component file', () => {
    const source = apiFile(`
  const tooltipProps = [{ name: 'text', type: 'string' }]

  const tooltipBubbleProps = [{ name: 'side', type: 'string' }]`)

    expect(parseApiTables(source, 'Tooltip').map((t) => t.component)).toEqual([
      'Tooltip',
      'TooltipBubble',
    ])
  })

  it('takes the component name from the folder for a single-component file', () => {
    const source = apiFile(`
  const propsData = [{ name: 'columns', type: 'Column[]' }]`)

    expect(parseApiTables(source, 'list')[0].component).toBe('List')
  })
})

describe('diffApiTables', () => {
  it('passes when only the row order differs', () => {
    const reordered = apiFile(`
  const propsData = [
  {
    name: 'type',
    description: 'Visual tone of the toast',
    required: false,
    type: '"error" | "success" | "info" | "warning"'
  },
  {
    name: 'title',
    description: 'Main line of the toast.',
    required: false,
    type: 'string',
    default: '""'
  }
]

  const emitsData = [
  {
    name: 'update:open',
    description: 'Fired when the open state changes.',
    type: '[value: boolean]'
  },
  {
    name: 'close',
    description: 'Fired when the component closes.',
    type: '[]'
  }
]`)

    expect(diffAgainstToast(reordered)).toEqual([])
  })

  it('passes when only the union member order differs', () => {
    const reordered = TOAST.replace(
      '"error" | "success" | "info" | "warning"',
      '"warning" | "info" | "error" | "success"',
    )

    expect(diffAgainstToast(reordered)).toEqual([])
  })

  it('fails when a prop is added', () => {
    const added = TOAST.replace(
      '    type: \'"error" | "success" | "info" | "warning"\'\n  }\n]',
      '    type: \'"error" | "success" | "info" | "warning"\'\n  },\n  {\n    name: \'icon\',\n    required: false,\n    type: \'string\'\n  }\n]',
    )

    expect(diffAgainstToast(added)).toEqual([
      {
        type: 'added',
        component: 'Toast',
        kind: 'prop',
        name: 'icon',
        fields: { required: 'false', type: 'string' },
      },
    ])
  })

  it('fails when a prop is removed', () => {
    const removed = apiFile(`
  const propsData = [
  {
    name: 'type',
    description: 'Visual tone of the toast',
    required: false,
    type: '"error" | "success" | "info" | "warning"'
  }
]

  const emitsData = [
  {
    name: 'close',
    description: 'Fired when the component closes.',
    type: '[]'
  },
  {
    name: 'update:open',
    description: 'Fired when the open state changes.',
    type: '[value: boolean]'
  }
]`)

    expect(diffAgainstToast(removed)).toEqual([
      { type: 'removed', component: 'Toast', kind: 'prop', name: 'title' },
    ])
  })

  it('fails when a prop is renamed', () => {
    const renamed = TOAST.replace("name: 'title'", "name: 'heading'")

    expect(diffAgainstToast(renamed)).toEqual([
      {
        type: 'added',
        component: 'Toast',
        kind: 'prop',
        name: 'heading',
        fields: {
          description: 'Main line of the toast.',
          required: 'false',
          type: 'string',
          default: '""',
        },
      },
      { type: 'removed', component: 'Toast', kind: 'prop', name: 'title' },
    ])
  })

  it('fails when a type changes', () => {
    const changed = TOAST.replace(
      '"error" | "success" | "info" | "warning"',
      '"error" | "success" | "info"',
    )

    expect(diffAgainstToast(changed)).toEqual([
      {
        type: 'changed',
        component: 'Toast',
        kind: 'prop',
        name: 'type',
        field: 'type',
        committed: '"error" | "success" | "info" | "warning"',
        current: '"error" | "success" | "info"',
      },
    ])
  })

  it('fails when a default changes', () => {
    const changed = TOAST.replace('default: \'""\'', 'default: \'"Heads up"\'')

    expect(diffAgainstToast(changed)).toEqual([
      {
        type: 'changed',
        component: 'Toast',
        kind: 'prop',
        name: 'title',
        field: 'default',
        committed: '""',
        current: '"Heads up"',
      },
    ])
  })

  it('fails when a default is dropped', () => {
    const changed = TOAST.replace(',\n    default: \'""\'', '')

    expect(diffAgainstToast(changed)).toEqual([
      {
        type: 'changed',
        component: 'Toast',
        kind: 'prop',
        name: 'title',
        field: 'default',
        committed: '""',
        current: undefined,
      },
    ])
  })

  it('fails when a description changes', () => {
    const changed = TOAST.replace(
      'Main line of the toast.',
      'Headline of the toast.',
    )

    expect(diffAgainstToast(changed)).toEqual([
      {
        type: 'changed',
        component: 'Toast',
        kind: 'prop',
        name: 'title',
        field: 'description',
        committed: 'Main line of the toast.',
        current: 'Headline of the toast.',
      },
    ])
  })

  it('fails when an emit changes', () => {
    const changed = TOAST.replace('[value: boolean]', '[open: boolean]')

    expect(diffAgainstToast(changed)).toEqual([
      {
        type: 'changed',
        component: 'Toast',
        kind: 'emit',
        name: 'update:open',
        field: 'type',
        committed: '[value: boolean]',
        current: '[open: boolean]',
      },
    ])
  })

  it('reports every difference, not just the first', () => {
    const changed = TOAST.replace("name: 'title'", "name: 'heading'").replace(
      '"error" | "success" | "info" | "warning"',
      '"error"',
    )

    expect(diffAgainstToast(changed).map((d) => [d.type, d.name])).toEqual([
      ['added', 'heading'],
      ['removed', 'title'],
      ['changed', 'type'],
    ])
  })
})

describe('failure messages', () => {
  it('names the component, the entry and what differs', () => {
    const changed = TOAST.replace(
      '"error" | "success" | "info" | "warning"',
      '"error" | "success" | "info"',
    )

    expect(formatDifferences(diffAgainstToast(changed))).toBe(
      [
        '  Toast prop `type` has a different type',
        '      committed: "\\"error\\" | \\"success\\" | \\"info\\" | \\"warning\\""',
        '      now:       "\\"error\\" | \\"success\\" | \\"info\\""',
      ].join('\n'),
    )
  })

  it('lists the fields of an entry that is missing from the committed table', () => {
    const added = TOAST.replace(
      "    type: 'string',\n    default: '\"\"'\n  },",
      "    type: 'string',\n    default: '\"\"'\n  },\n  {\n    name: 'icon',\n    type: 'string'\n  },",
    )

    expect(formatDifferences(diffAgainstToast(added))).toBe(
      [
        '  Toast prop `icon` is missing from the committed table',
        '      type: "string"',
      ].join('\n'),
    )
  })

  it('fits a removal onto one line for a CI annotation', () => {
    const removed = TOAST.replace(
      "  {\n    name: 'close',\n    description: 'Fired when the component closes.',\n    type: '[]'\n  },\n",
      '',
    )

    expect(diffAgainstToast(removed).map(summarizeDifference)).toEqual([
      'Toast emit `close` is in the committed table but no longer exists',
    ])
  })
})

describe('normalizeUnionOrder', () => {
  it('canonicalises a flat union', () => {
    expect(normalizeUnionOrder('"top" | "right" | "bottom" | "left"')).toBe(
      normalizeUnionOrder('"bottom" | "left" | "right" | "top"'),
    )
  })

  it('canonicalises a union nested in an object member', () => {
    expect(normalizeUnionOrder('{ direction: "desc" | "asc" | null; }')).toBe(
      '{ direction: "asc" | "desc" | null; }',
    )
  })

  it('canonicalises a union nested in a tuple element', () => {
    expect(normalizeUnionOrder('[value: string | number]')).toBe(
      '[value: number | string]',
    )
  })

  it('canonicalises a parenthesised arrow member', () => {
    expect(normalizeUnionOrder('string | ((item: T) => PropertyKey)')).toBe(
      '((item: T) => PropertyKey) | string',
    )
  })

  it('keeps the order of a union whose members carry position', () => {
    // The arrow is not bracketed, so its return type is the union. Moving
    // `number` in front of it would change what the type means.
    expect(normalizeUnionOrder('(item: T) => string | number')).toBe(
      '(item: T) => string | number',
    )
  })

  it('leaves a bare type alone', () => {
    expect(normalizeUnionOrder('Record<string, number>')).toBe(
      'Record<string, number>',
    )
  })

  it('does not treat a pipe inside a string literal as a separator', () => {
    expect(normalizeUnionOrder('"b|a" | "a"')).toBe('"a" | "b|a"')
  })

  it('leaves a truncated type unchanged rather than throwing', () => {
    const truncated = '{ editor: { contentComponent: { uid: number; type: Fun'
    expect(() => normalizeUnionOrder(truncated)).not.toThrow()
  })
})

describe('splitUnionMembers', () => {
  it('splits a flat union', () => {
    expect(splitUnionMembers('"top" | "right" | "bottom"')).toEqual([
      '"top"',
      '"right"',
      '"bottom"',
    ])
  })

  it('ignores a pipe nested in brackets or a string literal', () => {
    expect(splitUnionMembers('Record<string, "a" | "b"> | "c|d"')).toEqual([
      'Record<string, "a" | "b">',
      '"c|d"',
    ])
  })

  it('returns one member for a type that is not a union', () => {
    expect(splitUnionMembers('(item: T) => string')).toEqual([
      '(item: T) => string',
    ])
  })
})
