import * as url from 'url'
import path from 'path'
import fs from 'fs'

import type { MetaCheckerOptions } from 'vue-component-meta'
import { createChecker } from 'vue-component-meta'

const __dirname = url.fileURLToPath(new URL('.', import.meta.url))

const checkerOptions: MetaCheckerOptions = {
  forceUseTs: true,
  schema: { ignore: ['MyIgnoredNestedProps'] },
  printer: { newLine: 1 },
}

const tsconfigChecker = createChecker(
  path.join(__dirname, '../../tsconfig.json'),
  checkerOptions,
)

// test meta obj for single component
// const componentPath = path.join(
//   __dirname,
//   '../../src/components/Alert/Alert.vue',
// )
// const meta = tsconfigChecker.getComponentMeta(componentPath)

const ParseTypeStr = (type: string) => {
  const hasUndefined = type.includes('undefined')
  if (hasUndefined) {
    return type.replace(' | undefined', '').trim()
  }
	return type
}

const arrToStr = (arr) => JSON.stringify(arr, null, 2)

const genMetaTable = (data) => {
  let markupStr = `
<!-- Auto Generated by scripts/propsgen.ts -->

<script setup>
  import PropsTable from '@/components/Docs/PropsTable.vue'
  import SlotsTable from '@/components/Docs/SlotsTable.vue'
  import EmitsTable from '@/components/Docs/EmitsTable.vue'
</script>

## Props 
`
  const props = data.props.filter((x) => !x.global)
  const arrProps = props.map((x) => ({
    name: x.name,
    description: x.description,
    required: x.required,
    type: ParseTypeStr(x.type),
    default: x.default,
  }))

  if (arrProps.length > 0)
    markupStr += `<PropsTable :data='${arrToStr(arrProps)}'/> \n\n`

  const slots = data.slots.filter((x) => !x.global)
  const arrSlots = slots.map((x) => ({
    name: x.name,
    description: x.description,
    type: x.type.slice(0, 100),
  }))

  if (arrSlots.length > 0)
    markupStr += `## Default Slots \n <SlotsTable :data='${arrToStr(arrSlots)}'/> \n\n`

  const emits = data.events.filter((x) => !x.global)
  const arrEmits = emits.map((x) => ({
    name: x.name,
    description: x.description,
    type: x.type,
  }))

  if (arrEmits.length > 0)
    markupStr += `## Emit Events \n <EmitsTable :data='${arrToStr(arrEmits)}'/> \n\n`

  return markupStr
}

const componentDir = path.join(__dirname, '../../src/components')
const components = fs.readdirSync(componentDir)

// only include dirs as they have story files
const list = components.filter((x) => !x.includes('.vue'))

list.forEach((x) => {
  try {
    const fullpath = `../../src/components/${x}/${x}.vue`
    const componentPath = path.join(__dirname, fullpath)
    const meta = tsconfigChecker.getComponentMeta(componentPath)

    const metaFilePath = path.join(__dirname, `../meta/${x}.md`)
    const str = genMetaTable(meta)
    fs.writeFileSync(metaFilePath, str)
    console.log(`Generated ${x} meta`)
  } catch (e) {
    // TODO few components dont have default exposts
    console.error('-----------------------------\n', x, ':', e)
  }
})
