import * as url from 'url'
import path from 'path'
import fs from 'fs'

import type { MetaCheckerOptions } from 'vue-component-meta'
import { createChecker } from 'vue-component-meta'

const __dirname = url.fileURLToPath(new URL('.', import.meta.url))

const checkerOptions: MetaCheckerOptions = {
  forceUseTs: true,
  schema: { ignore: ['MyIgnoredNestedProps'] },
  printer: { newLine: 1 },
}

const tsconfigChecker = createChecker(
  path.join(__dirname, '../../tsconfig.json'),
  checkerOptions,
)

const componentDir = path.join(__dirname, '../../src/components')
const docsComponentsDir = path.join(__dirname, '../content/docs/components')
const AUTO_STORIES_START = '<!-- AUTO-GENERATED STORIES START -->'
const AUTO_STORIES_END = '<!-- AUTO-GENERATED STORIES END -->'

function parseTypeStr(type: string) {
  if (type.includes('undefined')) {
    return type.replace(' | undefined', '').trim()
  }
  return type
}

function arrToStr(arr: unknown) {
  return JSON.stringify(arr, null, 2)
}

function humanizeStoryName(name: string) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/[-_]/g, ' ')
    .trim()
}

function parseStoryFileName(fileName: string) {
  const storyFileName = fileName.replace(/\.vue$/, '')
  const orderedMatch = storyFileName.match(/^(\d+)[-_](.+)$/)

  if (!orderedMatch) {
    return {
      fileName: storyFileName,
      title: humanizeStoryName(storyFileName),
      order: null as number | null,
    }
  }

  return {
    fileName: storyFileName,
    title: humanizeStoryName(orderedMatch[2]),
    order: Number(orderedMatch[1]),
  }
}

function sortStories(
  stories: Array<{ fileName: string; title: string; order: number | null }>,
) {
  return [...stories].sort((a, b) => {
    if (a.order != null || b.order != null) {
      if (a.order == null) return 1
      if (b.order == null) return -1
      if (a.order !== b.order) return a.order - b.order
    }

    return a.title.localeCompare(b.title)
  })
}

function genMetaTable(name: string, data: any) {
  let markupStr = `<!-- Auto Generated by scripts/propsgen.ts -->
<script setup>
  import PropsTable from '@/components/Docs/PropsTable.vue'
  import SlotsTable from '@/components/Docs/SlotsTable.vue'
  import EmitsTable from '@/components/Docs/EmitsTable.vue'
</script>
`

  const props = data.props.filter((x: any) => !x.global)
  const arrProps = props.map((x: any) => ({
    name: x.name,
    description: x.description,
    required: x.required,
    type: parseTypeStr(x.type),
    default: x.default,
  }))

  if (arrProps.length > 0) {
    markupStr += `<PropsTable name="${name}" :data='${arrToStr(arrProps)}'/> \n\n`
  }

  const slots = data.slots.filter((x: any) => !x.global)
  const arrSlots = slots.map((x: any) => ({
    name: x.name,
    description: x.description,
    type: x.type.slice(0, 100),
  }))

  if (arrSlots.length > 0) {
    markupStr += `## Slots \n <SlotsTable :data='${arrToStr(arrSlots)}'/> \n\n`
  }

  const emits = data.events.filter((x: any) => !x.global)
  const arrEmits = emits.map((x: any) => ({
    name: x.name,
    description: x.description,
    type: x.type,
  }))

  if (arrEmits.length > 0) {
    markupStr += `## Emit Events \n <EmitsTable :data='${arrToStr(arrEmits)}'/> \n\n`
  }

  return markupStr
}

function getAvailableComponents() {
  return fs
    .readdirSync(componentDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => {
      return fs.existsSync(path.join(componentDir, name, `${name}.vue`))
    })
    .sort((a, b) => a.localeCompare(b))
}

function getStories(componentName: string) {
  const storiesDir = path.join(componentDir, componentName, 'stories')

  if (!fs.existsSync(storiesDir)) {
    return []
  }

  return sortStories(
    fs
      .readdirSync(storiesDir)
      .filter((file) => file.endsWith('.vue'))
      .map((file) => parseStoryFileName(file)),
  )
}

function getStoryPreviewMarkup(componentName: string) {
  return getStories(componentName)
    .map((story) => {
      return `## ${story.title}\n<ComponentPreview name="${componentName}-${story.fileName}" />`
    })
    .join('\n\n')
}

function replaceAutoGeneratedSection(content: string, replacement: string) {
  const startIndex = content.indexOf(AUTO_STORIES_START)
  const endIndex = content.indexOf(AUTO_STORIES_END)

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    return content
  }

  const before = content.slice(0, startIndex)
  const after = content.slice(endIndex + AUTO_STORIES_END.length)
  return `${before}${replacement}${after}`
}

function syncComponentDocsStories(componentName: string) {
  const docsPath = path.join(docsComponentsDir, `${componentName.toLowerCase()}.md`)

  if (!fs.existsSync(docsPath)) {
    return
  }

  const content = fs.readFileSync(docsPath, 'utf8')
  if (!content.includes(AUTO_STORIES_START) || !content.includes(AUTO_STORIES_END)) {
    return
  }

  const storiesMarkup = getStoryPreviewMarkup(componentName)
  const replacement = `${AUTO_STORIES_START}\n${storiesMarkup}\n${AUTO_STORIES_END}`
  const nextContent = replaceAutoGeneratedSection(content, replacement)

  if (nextContent !== content) {
    fs.writeFileSync(docsPath, nextContent)
    console.log(`Synced ${componentName} docs stories`)
  }
}

function parseRequestedComponents(availableComponents: string[]) {
  const availableByLowerName = new Map(
    availableComponents.map((name) => [name.toLowerCase(), name]),
  )

  const args = process.argv.slice(2).filter((arg) => arg !== '--')
  const rawNames = args.flatMap((arg) => {
    if (arg === '--all') return []
    if (arg.startsWith('--components=')) {
      return arg
        .slice('--components='.length)
        .split(',')
        .map((name) => name.trim())
        .filter(Boolean)
    }
    if (arg.startsWith('--')) return []
    return arg
      .split(',')
      .map((name) => name.trim())
      .filter(Boolean)
  })

  if (args.includes('--all') || rawNames.length === 0) {
    return availableComponents
  }

  const unknownNames = rawNames.filter(
    (name) => !availableByLowerName.has(name.toLowerCase()),
  )

  if (unknownNames.length) {
    console.error(
      `Unknown component(s): ${unknownNames.join(', ')}\nAvailable: ${availableComponents.join(', ')}`,
    )
    process.exit(1)
  }

  return [
    ...new Set(rawNames.map((name) => availableByLowerName.get(name.toLowerCase())!)),
  ]
}

const availableComponents = getAvailableComponents()
const selectedComponents = parseRequestedComponents(availableComponents)

console.log(`Generating docs meta for: ${selectedComponents.join(', ')}`)

selectedComponents.forEach((name) => {
  try {
    const componentPath = path.join(componentDir, name, `${name}.vue`)
    const meta = tsconfigChecker.getComponentMeta(componentPath)

    const metaFilePath = path.join(__dirname, `../meta/${name}.md`)
    const str = genMetaTable(name, meta)
    fs.writeFileSync(metaFilePath, str)
    console.log(`Generated ${name} meta`)

    syncComponentDocsStories(name)
  } catch (error) {
    console.error('-----------------------------\n', name, ':', error)
    process.exitCode = 1
  }
})
