import fs from 'node:fs'
import path from 'node:path'
import type { Plugin, ViteDevServer } from 'vite'

// Author-facing layout: each component owns its docs:
//   src/components/Button/Button.md      (hand-written)
//   src/components/Button/Button.api.md  (auto-generated by propsgen)
//   frappe/Link/Link.md                  (Frappe-integrated controls)
//
// VitePress wants every page under its srcDir (`docs/content`). Instead of
// reshaping srcDir or rewrites, this plugin keeps a thin proxy file at
//   docs/content/docs/components/<name>.md
//   docs/content/docs/frappe/<name>.md
// that simply `@include`s the colocated source. The proxy is auto-managed
// — never edit it by hand.

const COMPONENTS_DIR = path.resolve(__dirname, '../../../src/components')
const COMPONENT_PROXIES_DIR = path.resolve(
  __dirname,
  '../../content/docs/components',
)
const FRAPPE_DIR = path.resolve(__dirname, '../../../frappe')
const FRAPPE_PROXIES_DIR = path.resolve(__dirname, '../../content/docs/frappe')

const SOURCE_ROOTS: Array<{ sourceDir: string; proxyDir: string }> = [
  { sourceDir: COMPONENTS_DIR, proxyDir: COMPONENT_PROXIES_DIR },
  { sourceDir: FRAPPE_DIR, proxyDir: FRAPPE_PROXIES_DIR },
]

const PROXY_HEADER =
  '<!-- AUTO-GENERATED by colocatedComponentDocs — do not edit. Source: '

interface Entry {
  name: string // 'Button'
  source: string // absolute path to src/components/Button/Button.md
  proxy: string // absolute path to docs/content/docs/components/button.md
  proxyDir: string // absolute path to the proxy root that owns this entry
}

function discover(sourceDir: string, proxyDir: string): Entry[] {
  if (!fs.existsSync(sourceDir)) return []
  const entries: Entry[] = []
  for (const name of fs.readdirSync(sourceDir)) {
    const source = path.join(sourceDir, name, `${name}.md`)
    if (!fs.existsSync(source)) continue
    entries.push({
      name,
      source,
      proxy: path.join(proxyDir, `${name.toLowerCase()}.md`),
      proxyDir,
    })
  }
  return entries
}

function proxyContent(entry: Entry) {
  const includePath = path
    .relative(path.dirname(entry.proxy), entry.source)
    .split(path.sep)
    .join('/')
  const sourceRel = path
    .relative(entry.proxyDir, entry.source)
    .split(path.sep)
    .join('/')
  return `${PROXY_HEADER}${sourceRel} -->\n<!-- @include: ${includePath} -->\n`
}

function isManagedProxy(filePath: string) {
  if (!fs.existsSync(filePath)) return false
  const first = fs.readFileSync(filePath, 'utf-8').split('\n', 1)[0] ?? ''
  return first.startsWith(PROXY_HEADER)
}

function writeIfChanged(filePath: string, content: string) {
  if (fs.existsSync(filePath)) {
    const current = fs.readFileSync(filePath, 'utf-8')
    if (current === content) return false
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
  return true
}

export function syncColocatedComponentDocs() {
  const allEntries: Entry[] = []

  for (const { sourceDir, proxyDir } of SOURCE_ROOTS) {
    const entries = discover(sourceDir, proxyDir)
    allEntries.push(...entries)
    const expected = new Set(entries.map((e) => e.proxy))

    for (const entry of entries) {
      writeIfChanged(entry.proxy, proxyContent(entry))
    }

    // Remove orphan proxies — only those we created (header check), so
    // hand-written legacy pages like badge.md, legacy.md stay untouched.
    if (fs.existsSync(proxyDir)) {
      for (const name of fs.readdirSync(proxyDir)) {
        const filePath = path.join(proxyDir, name)
        if (expected.has(filePath)) continue
        if (isManagedProxy(filePath)) fs.unlinkSync(filePath)
      }
    }
  }

  return allEntries
}

const syncAll = syncColocatedComponentDocs

export default function colocatedComponentDocs(): Plugin {
  return {
    name: 'colocated-component-docs',
    enforce: 'pre',
    buildStart() {
      syncAll()
    },
    configureServer(server: ViteDevServer) {
      syncAll()
      const onChange = (file: string) => {
        const matchesRoot = SOURCE_ROOTS.some(({ sourceDir }) =>
          file.startsWith(sourceDir),
        )
        if (!matchesRoot) return
        if (!file.endsWith('.md')) return
        syncAll()
      }
      server.watcher.on('add', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
