import fs from 'node:fs'
import path from 'node:path'
import type { Plugin, ViteDevServer } from 'vite'

// Author-facing layout: each component owns its docs:
//   src/components/Button/Button.md      (hand-written)
//   src/components/Button/Button.api.md  (auto-generated by propsgen)
//
// VitePress wants every page under its srcDir (`docs/content`). Instead of
// reshaping srcDir or rewrites, this plugin keeps a thin proxy file at
//   docs/content/docs/components/<name>.md
// that simply `@include`s the colocated source. The proxy is auto-managed
// — never edit it by hand.

const COMPONENTS_DIR = path.resolve(__dirname, '../../../src/components')
const PROXIES_DIR = path.resolve(__dirname, '../../content/docs/components')

const PROXY_HEADER =
  '<!-- AUTO-GENERATED by colocatedComponentDocs — do not edit. Source: '

interface Entry {
  name: string // 'Button'
  source: string // absolute path to src/components/Button/Button.md
  proxy: string // absolute path to docs/content/docs/components/button.md
}

function discover(): Entry[] {
  if (!fs.existsSync(COMPONENTS_DIR)) return []
  const entries: Entry[] = []
  for (const name of fs.readdirSync(COMPONENTS_DIR)) {
    const source = path.join(COMPONENTS_DIR, name, `${name}.md`)
    if (!fs.existsSync(source)) continue
    entries.push({
      name,
      source,
      proxy: path.join(PROXIES_DIR, `${name.toLowerCase()}.md`),
    })
  }
  return entries
}

function proxyContent(entry: Entry) {
  const includePath = path
    .relative(path.dirname(entry.proxy), entry.source)
    .split(path.sep)
    .join('/')
  const sourceRel = path
    .relative(PROXIES_DIR, entry.source)
    .split(path.sep)
    .join('/')
  return `${PROXY_HEADER}${sourceRel} -->\n<!-- @include: ${includePath} -->\n`
}

function isManagedProxy(filePath: string) {
  if (!fs.existsSync(filePath)) return false
  const first = fs.readFileSync(filePath, 'utf-8').split('\n', 1)[0] ?? ''
  return first.startsWith(PROXY_HEADER)
}

function writeIfChanged(filePath: string, content: string) {
  if (fs.existsSync(filePath)) {
    const current = fs.readFileSync(filePath, 'utf-8')
    if (current === content) return false
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content, 'utf-8')
  return true
}

export function syncColocatedComponentDocs() {
  const entries = discover()
  const expected = new Set(entries.map((e) => e.proxy))

  for (const entry of entries) {
    writeIfChanged(entry.proxy, proxyContent(entry))
  }

  // Remove orphan proxies — only those we created (header check), so
  // hand-written legacy pages like badge.md, legacy.md stay untouched.
  if (fs.existsSync(PROXIES_DIR)) {
    for (const name of fs.readdirSync(PROXIES_DIR)) {
      const filePath = path.join(PROXIES_DIR, name)
      if (expected.has(filePath)) continue
      if (isManagedProxy(filePath)) fs.unlinkSync(filePath)
    }
  }

  return entries
}

const syncAll = syncColocatedComponentDocs

export default function colocatedComponentDocs(): Plugin {
  return {
    name: 'colocated-component-docs',
    enforce: 'pre',
    buildStart() {
      syncAll()
    },
    configureServer(server: ViteDevServer) {
      syncAll()
      const onChange = (file: string) => {
        if (!file.startsWith(COMPONENTS_DIR)) return
        if (!file.endsWith('.md')) return
        syncAll()
      }
      server.watcher.on('add', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
